// web/src/app/reset/page.tsx
"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { apiGet } from "@/lib/api";

export default function ResetPage() {
  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [successMsg, setSuccessMsg] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSuccessMsg("");
    setErrorMsg("");
    if (!email) {
      setErrorMsg("请输入邮箱地址");
      return;
    }
    setLoading(true);
    try {
      const res = await apiGet(`/api/reset_password?email=${encodeURIComponent(email)}`);
      if (res?.success) {
        setSuccessMsg("重置邮件已发送，请检查邮箱");
        setEmail("");
      } else {
        setErrorMsg(res?.message || "发送失败");
      }
    } catch {
      setErrorMsg("请求失败，请稍后重试");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="auth-page">
      <div className="auth-shell">
        <div className="auth-card">
          <h1 className="auth-title">密码重置</h1>
          <div className="auth-body">
            <form className="space-y-3" onSubmit={handleSubmit}>
              <div>
                <label className="auth-label" htmlFor="reset-email">邮箱</label>
                <input id="reset-email" className="auth-input" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" placeholder="请输入邮箱地址" />
              </div>
              {errorMsg ? <p className="text-sm text-red-500">{errorMsg}</p> : null}
              {successMsg ? <p className="text-sm text-emerald-600">{successMsg}</p> : null}
              <div className="auth-actions">
                <button className="btn w-full" type="submit" disabled={loading}>{loading ? "提交中..." : "提交"}</button>
              </div>
            </form>
            <div className="mt-6 text-center text-sm">
              <Link className="text-blue-600" href="/login">返回登录</Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// web-archive/src/routes/reset/+page.svelte
<svelte:options runes={false} />

<script>
  import { apiGet } from '$lib/api';

  let email = '';
  let loading = false;
  let successMsg = '';
  let errorMsg = '';

  /**
   * @param {SubmitEvent} event
   */
  async function handleSubmit(event) {
    event.preventDefault();
    successMsg = '';
    errorMsg = '';

    if (!email) {
      errorMsg = '请输入邮箱地址';
      return;
    }

    loading = true;
    try {
      const res = await apiGet(`/api/reset_password?email=${encodeURIComponent(email)}`);
      if (res?.success) {
        successMsg = '重置邮件已发送，请检查邮箱';
        email = '';
      } else {
        errorMsg = res?.message || '发送失败';
      }
    } catch (err) {
      errorMsg = '请求失败，请稍后重试';
    } finally {
      loading = false;
    }
  }
</script>

<div class="auth-page">
  <div class="auth-shell">
    <div class="auth-card">
      <h1 class="auth-title">密码重置</h1>
      <div class="auth-body">
        <form class="space-y-3" onsubmit={handleSubmit}>
          <div>
            <label class="auth-label" for="reset-email">邮箱</label>
            <input id="reset-email" class="auth-input" type="email" bind:value={email} autocomplete="email" placeholder="请输入邮箱地址" />
          </div>

          {#if errorMsg}
            <p class="text-sm text-red-500">{errorMsg}</p>
          {/if}
          {#if successMsg}
            <p class="text-sm text-green-600">{successMsg}</p>
          {/if}

          <div class="auth-actions">
            <button class="w-full rounded-none bg-black text-white h-10 disabled:opacity-60" type="submit" disabled={loading}>
              {loading ? '提交中...' : '提交'}
            </button>
          </div>
        </form>

        <div class="mt-6 text-center text-sm">
          <a class="text-blue-600 hover:text-blue-800" href="/login">返回登录</a>
        </div>
      </div>
    </div>
  </div>
</div>
