// web/src/components/dashboard/api-keys-panel.tsx
"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { apiDelete, apiGet, apiPost } from "@/lib/api";
import { useToast } from "@/components/ui/toast-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

type TokenItem = {
  id: number;
  key?: string;
  name?: string;
  status?: number;
  unlimited_quota?: boolean;
  remain_quota?: number;
  expired_time?: number;
};

function renderQuota(value: number): string {
  const quotaPerUnit = Number(localStorage.getItem("quota_per_unit") || "500000");
  const usd =
    value /
    (Number.isFinite(quotaPerUnit) && quotaPerUnit > 0 ? quotaPerUnit : 500000);
  if (!Number.isFinite(usd) || usd <= 0) return "$0.00";
  return `$${usd.toFixed(2)}`;
}

function formatDate(ts?: number) {
  if (ts === -1 || !ts) return "不过期";
  const date = new Date(ts * 1000);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString();
}

function usdToQuota(usd: number): number {
  const quotaPerUnit = Number(localStorage.getItem("quota_per_unit") || "500000");
  const valid = Number.isFinite(quotaPerUnit) && quotaPerUnit > 0 ? quotaPerUnit : 500000;
  return Math.round(usd * valid);
}

function maskedKeyLabel(token: TokenItem): string {
  const key = String(token.key || "").trim();
  if (!key) return "—";
  return key.startsWith("sk-") ? key : `sk-${key}`;
}

const EXPIRATION_OPTIONS = [
  { value: "never", label: "永不过期" },
  { value: "1h", label: "1 小时" },
  { value: "1d", label: "1 天" },
  { value: "1m", label: "1 个月" },
] as const;

function buildExpiredTime(option: string): number {
  const now = Math.floor(Date.now() / 1000);
  if (option === "1h") return now + 3600;
  if (option === "1d") return now + 86400;
  if (option === "1m") return now + 30 * 86400;
  return -1;
}

export function ApiKeysPanel() {
  const { showError, showSuccess } = useToast();
  const showErrorRef = useRef(showError);
  const [tokens, setTokens] = useState<TokenItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const [pendingDeleteId, setPendingDeleteId] = useState<number | null>(null);
  const [form, setForm] = useState({
    name: "",
    remain_quota: "",
    expired_time: "never",
  });
  const [deleting, setDeleting] = useState(false);

  useEffect(() => {
    showErrorRef.current = showError;
  }, [showError]);

  const loadTokens = useCallback(async () => {
    setLoading(true);
    try {
      const res = await apiGet("/api/token?p=1&size=100");
      if (!res?.success) {
        showErrorRef.current(res?.message || "加载密钥失败");
        return;
      }
      const data = Array.isArray(res.data) ? res.data : res.data?.items || [];
      setTokens(data);
    } catch {
      showErrorRef.current("加载密钥失败");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadTokens();
  }, [loadTokens]);

  async function createToken() {
    if (!form.name.trim()) {
      showError("请输入密钥名称");
      return;
    }
    const rawRemain = String(form.remain_quota || "").trim();
    const unlimited = rawRemain === "";
    let remainQuota = 0;
    if (!unlimited) {
      const usd = parseFloat(rawRemain);
      if (!Number.isFinite(usd) || usd < 0) {
        showError("额度上限金额无效");
        return;
      }
      remainQuota = usdToQuota(usd);
    }

    setCreating(true);
    try {
      const res = await apiPost("/api/token", {
        name: form.name.trim(),
        unlimited_quota: unlimited,
        remain_quota: remainQuota,
        expired_time: buildExpiredTime(form.expired_time),
      });
      if (res?.success) {
        setForm({ name: "", remain_quota: "", expired_time: "never" });
        setShowCreateDialog(false);
        showSuccess("密钥创建成功");
        await loadTokens();
      } else {
        showError(res?.message || "创建失败");
      }
    } finally {
      setCreating(false);
    }
  }

  async function copyTokenKey(id: number) {
    const res = await apiPost(`/api/token/${id}/key`, {});
    const key = res?.data?.key ? `sk-${res.data.key}` : "";
    if (!res?.success || !key) {
      showError(res?.message || "获取密钥失败");
      return;
    }
    await navigator.clipboard.writeText(key);
    showSuccess("密钥已复制");
  }

  async function removeToken(id: number) {
    setDeleting(true);
    const res = await apiDelete(`/api/token/${id}`);
    setDeleting(false);
    if (!res?.success) {
      showError(res?.message || "删除失败");
      return;
    }
    showSuccess("密钥已删除");
    await loadTokens();
  }

  return (
    <>
      <section className="panel w-full min-w-0">
        <div className="panel-header flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <h2 className="panel-title">API 密钥</h2>
          <div className="flex flex-wrap items-center justify-end gap-2 sm:ml-auto">
            <Button variant="outline" size="sm" onClick={() => void loadTokens()} disabled={loading}>
              {loading ? "刷新中..." : "刷新"}
            </Button>
            <Button
              size="sm"
              onClick={() => {
                setForm({ name: "", remain_quota: "", expired_time: "never" });
                setShowCreateDialog(true);
              }}
            >
              添加令牌
            </Button>
          </div>
        </div>
        <div className="panel-body">
          {loading ? (
            <div className="text-sm opacity-70">加载中...</div>
          ) : tokens.length === 0 ? (
            <div className="text-sm opacity-70">暂无令牌数据</div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>密钥</TableHead>
                  <TableHead>名称</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>剩余额度</TableHead>
                  <TableHead>过期时间</TableHead>
                  <TableHead className="text-right">操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {tokens.map((token) => (
                  <TableRow key={token.id} className={token.status !== 1 ? "opacity-70" : ""}>
                    <TableCell className="max-w-[min(100%,18rem)] font-mono text-xs whitespace-normal break-all text-muted-foreground">
                      {maskedKeyLabel(token)}
                    </TableCell>
                    <TableCell>{token.name || "-"}</TableCell>
                    <TableCell>{token.status === 1 ? "启用" : "禁用"}</TableCell>
                    <TableCell>{token.unlimited_quota ? "无限制" : renderQuota(token.remain_quota ?? 0)}</TableCell>
                    <TableCell>{formatDate(token.expired_time)}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex flex-wrap items-center justify-end gap-1">
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => void copyTokenKey(token.id)}
                        >
                          复制
                        </Button>
                        <Button
                          type="button"
                          variant="destructive"
                          size="sm"
                          onClick={() => {
                            setPendingDeleteId(token.id);
                            setShowDeleteDialog(true);
                          }}
                        >
                          删除
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </div>
      </section>

      <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>创建密钥</DialogTitle>
          </DialogHeader>
          <div className="space-y-3">
            <div>
              <label className="auth-label" htmlFor="dash-token-name">
                名称
              </label>
              <Input
                id="dash-token-name"
                type="text"
                value={form.name}
                onChange={(event) => setForm((prev) => ({ ...prev, name: event.target.value }))}
                placeholder="请输入密钥名称，例如「聊天机器人」"
              />
            </div>
            <div>
              <label className="auth-label" htmlFor="dash-token-quota">
                额度上限（美元，可选）
              </label>
              <Input
                id="dash-token-quota"
                type="text"
                inputMode="decimal"
                autoComplete="off"
                value={form.remain_quota}
                onChange={(event) => setForm((prev) => ({ ...prev, remain_quota: event.target.value }))}
                placeholder="留空表示不限制"
              />
            </div>
            <div>
              <span className="auth-label mb-1 block">过期时间</span>
              <Select
                value={form.expired_time}
                onValueChange={(value) =>
                  setForm((prev) => ({ ...prev, expired_time: value || "never" }))
                }
              >
                <SelectTrigger id="dash-token-expire" className="w-full min-w-0 max-w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {EXPIRATION_OPTIONS.map((opt) => (
                    <SelectItem key={opt.value} value={opt.value}>
                      {opt.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" type="button" onClick={() => setShowCreateDialog(false)}>
              取消
            </Button>
            <Button type="button" disabled={creating} onClick={() => void createToken()}>
              {creating ? "创建中..." : "创建"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog
        open={showDeleteDialog}
        onOpenChange={(open) => {
          setShowDeleteDialog(open);
          if (!open) setPendingDeleteId(null);
        }}
      >
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>删除密钥</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">确定删除这个密钥吗？此操作不可恢复。</p>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setShowDeleteDialog(false)}>
              取消
            </Button>
            <Button
              variant="destructive"
              disabled={deleting || pendingDeleteId == null}
              onClick={() => {
                if (pendingDeleteId != null) void removeToken(pendingDeleteId);
              }}
            >
              {deleting ? "删除中..." : "删除"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

// web/src/lib/components/dashboard/ApiKeysPanel.svelte
<svelte:options runes={false} />

<script>
  import { onMount } from 'svelte';
  import { apiDelete, apiGet, apiPost } from '$lib/api';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Dialog from '$lib/components/ui/dialog';
  import * as AlertDialog from '$lib/components/ui/alert-dialog';
  import * as Select from '$lib/components/ui/select';
  import {
    Table,
    TableHeader,
    TableBody,
    TableRow,
    TableHead,
    TableCell
  } from '$lib/components/ui/table';
  import { renderQuota, usdToQuota, copy } from '$lib/dashboard/helpers.js';
  import { showSuccess, showError } from '$lib/dashboard/notify.js';

  let loading = true;
  let errorMsg = '';
  /** @type {any[]} */
  let tokens = [];
  let showModal = false;
  let saving = false;

  let showDeleteConfirm = false;
  /** @type {number | null} */
  let pendingDeleteId = null;

  let form = {
    name: '',
    remain_quota: '',
    expired_time: 'never'
  };

  const EXPIRATION_OPTIONS = [
    { value: 'never', label: '永不过期' },
    { value: '1h', label: '1 小时' },
    { value: '1d', label: '1 天' },
    { value: '1m', label: '1 个月' }
  ];

  /** @param {string} v */
  function expirationLabel(v) {
    return EXPIRATION_OPTIONS.find((o) => o.value === v)?.label ?? '永不过期';
  }

  async function loadTokens() {
    loading = true;
    errorMsg = '';
    try {
      const res = await apiGet('/api/token/?p=1&size=100');
      if (res?.success) {
        const data = res.data;
        tokens = Array.isArray(data) ? data : data?.items || [];
      } else {
        errorMsg = res?.message || '加载失败';
      }
    } catch (err) {
      errorMsg = '加载密钥失败';
    } finally {
      loading = false;
    }
  }

  /**
   * @param {number | null | undefined} ts
   */
  function formatDate(ts) {
    if (ts === -1 || !ts) return '不过期';
    const date = new Date(ts * 1000);
    if (Number.isNaN(date.getTime())) return '-';
    return date.toLocaleString();
  }

  /**
   * 列表接口已返回脱敏 key，与复制时的 sk- 前缀保持一致便于辨认
   * @param {any} token
   */
  function maskedKeyLabel(token) {
    const k = token?.key;
    if (k == null || String(k).trim() === '') return '—';
    const s = String(k);
    return s.startsWith('sk-') ? s : `sk-${s}`;
  }

  function openCreate() {
    form = { name: '', remain_quota: '', expired_time: 'never' };
    showModal = true;
  }

  /**
   * @param {string} option
   */
  function buildExpiredTime(option) {
    const now = Math.floor(Date.now() / 1000);
    if (option === '1h') return now + 3600;
    if (option === '1d') return now + 86400;
    if (option === '1m') return now + 30 * 86400;
    return -1;
  }

  /**
   * @param {SubmitEvent} event
   */
  async function submitForm(event) {
    event.preventDefault();
    if (!form.name.trim()) return;

    saving = true;
    try {
      const rawRemain = form.remain_quota;
      const unlimited =
        rawRemain === '' || rawRemain == null || String(rawRemain).trim() === '';
      let remainQuota = 0;
      if (!unlimited) {
        const usd = parseFloat(String(rawRemain));
        if (!Number.isFinite(usd) || usd < 0) {
          errorMsg = '金额无效';
          return;
        }
        remainQuota = usdToQuota(usd);
      }
      /** @type {Record<string, unknown>} */
      const payload = {
        name: form.name.trim(),
        unlimited_quota: unlimited,
        remain_quota: remainQuota,
        expired_time: buildExpiredTime(form.expired_time)
      };

      const res = await apiPost('/api/token/', payload);

      if (res?.success) {
        showModal = false;
        await loadTokens();
      } else {
        errorMsg = res?.message || '创建失败';
      }
    } catch (err) {
      errorMsg = '创建失败，请稍后重试';
    } finally {
      saving = false;
    }
  }

  /**
   * @param {number} id
   */
  function requestDeleteToken(id) {
    pendingDeleteId = id;
    showDeleteConfirm = true;
  }

  async function confirmDeleteToken() {
    if (pendingDeleteId == null) return;
    const id = pendingDeleteId;
    const res = await apiDelete(`/api/token/${id}/`);
    showDeleteConfirm = false;
    pendingDeleteId = null;
    if (res?.success) {
      await loadTokens();
    } else {
      errorMsg = res?.message || '删除失败';
    }
  }

  /**
   * @param {number} id
   */
  async function copyTokenKey(id) {
    const res = await apiPost(`/api/token/${id}/key`, {});
    if (!res?.success || !res?.data?.key) {
      errorMsg = res?.message || '获取密钥失败';
      return;
    }
    const ok = await copy(`sk-${res.data.key}`);
    if (ok) showSuccess('密钥已复制到剪贴板');
    else showError('复制失败');
  }

  onMount(loadTokens);
</script>

<div
  class="w-full min-w-0 overflow-hidden rounded-2xl border border-gray-200 bg-neutral-50 shadow-sm dark:border-zinc-700 dark:bg-zinc-950/70"
>
  <div
    class="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between md:p-6 md:pb-4"
  >
    <h2 class="text-lg font-semibold tracking-tight">API 密钥</h2>
    <div class="flex flex-wrap items-center justify-end gap-2 sm:ml-auto">
      <Button variant="outline" size="sm" onclick={loadTokens} disabled={loading}>
        {loading ? '刷新中...' : '刷新'}
      </Button>
      <Button size="sm" onclick={openCreate}>添加令牌</Button>
    </div>
  </div>

  <div class="border-t border-border" role="presentation"></div>

  <div class="p-4 md:p-6 md:pt-4">
    {#if errorMsg}
      <div class="mb-3 text-sm text-red-500">{errorMsg}</div>
    {/if}

    {#if loading}
      <div class="text-sm opacity-70">加载中...</div>
    {:else if tokens.length === 0}
      <div class="text-sm opacity-70">暂无令牌数据</div>
    {:else}
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead>密钥</TableHead>
            <TableHead>名称</TableHead>
            <TableHead>状态</TableHead>
            <TableHead>剩余额度</TableHead>
            <TableHead>过期时间</TableHead>
            <TableHead class="text-right">操作</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {#each tokens as token}
            <TableRow class={token.status !== 1 ? 'opacity-70' : ''}>
              <TableCell class="max-w-[min(100%,18rem)] font-mono text-xs whitespace-normal break-all text-muted-foreground">
                {maskedKeyLabel(token)}
              </TableCell>
              <TableCell>{token.name || '-'}</TableCell>
              <TableCell>{token.status === 1 ? '启用' : '禁用'}</TableCell>
              <TableCell>
                {token.unlimited_quota ? '无限制' : renderQuota(token.remain_quota ?? 0)}
              </TableCell>
              <TableCell>{formatDate(token.expired_time)}</TableCell>
              <TableCell class="text-right">
                <div class="flex flex-wrap items-center justify-end gap-1">
                  <Button variant="outline" size="xs" onclick={() => copyTokenKey(token.id)}>复制</Button>
                  <Button variant="destructive" size="xs" onclick={() => requestDeleteToken(token.id)}>删除</Button>
                </div>
              </TableCell>
            </TableRow>
          {/each}
        </TableBody>
      </Table>
    {/if}
  </div>
</div>

<Dialog.Root bind:open={showModal}>
  <Dialog.Content class="max-w-lg">
    <Dialog.Header>
      <Dialog.Title>创建密钥</Dialog.Title>
    </Dialog.Header>
    <form class="space-y-3" onsubmit={submitForm}>
      <div>
        <label class="auth-label" for="dash-token-name">名称</label>
        <Input
          id="dash-token-name"
          type="text"
          bind:value={form.name}
          placeholder={'请输入密钥名称，例如「聊天机器人」'}
        />
      </div>
      <div>
        <label class="auth-label" for="dash-token-quota">额度上限（美元，可选）</label>
        <Input
          id="dash-token-quota"
          type="text"
          inputmode="decimal"
          autocomplete="off"
          bind:value={form.remain_quota}
          placeholder="留空表示不限制"
        />
      </div>
      <div>
        <span class="auth-label mb-1 block">过期时间</span>
        <Select.Root type="single" bind:value={form.expired_time}>
          <Select.Trigger id="dash-token-expire" class="w-full min-w-0 max-w-full">
            <span class="truncate text-left">{expirationLabel(form.expired_time)}</span>
          </Select.Trigger>
          <Select.Content>
            {#each EXPIRATION_OPTIONS as opt}
              <Select.Item value={opt.value} label={opt.label}>{opt.label}</Select.Item>
            {/each}
          </Select.Content>
        </Select.Root>
      </div>
      <Dialog.Footer class="gap-2">
        <Button variant="outline" type="button" onclick={() => (showModal = false)}>取消</Button>
        <Button type="submit" disabled={saving}>{saving ? '创建中...' : '创建'}</Button>
      </Dialog.Footer>
    </form>
  </Dialog.Content>
</Dialog.Root>

<AlertDialog.Root bind:open={showDeleteConfirm}>
  <AlertDialog.Content class="max-w-md">
    <AlertDialog.Header>
      <AlertDialog.Title>删除密钥</AlertDialog.Title>
      <AlertDialog.Description>确定删除这个密钥吗？此操作不可恢复。</AlertDialog.Description>
    </AlertDialog.Header>
    <AlertDialog.Footer class="gap-2">
      <AlertDialog.Cancel>取消</AlertDialog.Cancel>
      <AlertDialog.Action variant="destructive" onclick={confirmDeleteToken}>删除</AlertDialog.Action>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>
