// web/src/lib/components/dashboard/TwoFASetting.svelte
<svelte:options runes={false} />

<script>
  import { apiGet, apiPost } from '$lib/api';
  import { showError, showSuccess, showWarning } from '$lib/dashboard/notify.js';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import * as Dialog from '$lib/components/ui/dialog';
  import QRCode from 'qrcode';
  import { onMount } from 'svelte';
  import { Shield, Warning, ArrowsClockwise, Copy } from 'phosphor-svelte';

  let loading = false;
  let status = {
    enabled: false,
    locked: false,
    backup_codes_remaining: 0,
  };

  let setupModalVisible = false;
  let disableModalVisible = false;
  let backupModalVisible = false;

  let setupData = null;
  let verificationCode = '';
  /** @type {string[]} */
  let backupCodes = [];
  let confirmDisable = false;
  let currentStep = 0;
  let qrDataUrl = '';

  async function fetchStatus() {
    try {
      const res = await apiGet('/api/user/2fa/status');
      if (res?.success) {
        status = res.data;
      }
    } catch (_) {
      showError('获取2FA状态失败');
    }
  }

  async function handleSetup2FA() {
    loading = true;
    try {
      const res = await apiPost('/api/user/2fa/setup', {});
      if (res?.success) {
        setupData = res.data;
        currentStep = 0;
        verificationCode = '';
        qrDataUrl = '';
        if (setupData?.qr_code_data) {
          qrDataUrl = await QRCode.toDataURL(setupData.qr_code_data, { width: 180, margin: 1 });
        }
        setupModalVisible = true;
      } else {
        showError(res?.message || '设置失败');
      }
    } catch (_) {
      showError('设置2FA失败');
    } finally {
      loading = false;
    }
  }

  async function handleEnable2FA() {
    if (!verificationCode) {
      showWarning('请输入验证码');
      return;
    }
    loading = true;
    try {
      const res = await apiPost('/api/user/2fa/enable', { code: verificationCode });
      if (res?.success) {
        showSuccess('两步验证启用成功！');
        setupModalVisible = false;
        setupData = null;
        verificationCode = '';
        currentStep = 0;
        await fetchStatus();
      } else {
        showError(res?.message || '启用失败');
      }
    } catch (_) {
      showError('启用2FA失败');
    } finally {
      loading = false;
    }
  }

  async function handleDisable2FA() {
    if (!verificationCode) {
      showWarning('请输入验证码或备用码');
      return;
    }
    if (!confirmDisable) {
      showWarning('请确认您已了解禁用两步验证的后果');
      return;
    }
    loading = true;
    try {
      const res = await apiPost('/api/user/2fa/disable', { code: verificationCode });
      if (res?.success) {
        showSuccess('两步验证已禁用');
        disableModalVisible = false;
        verificationCode = '';
        confirmDisable = false;
        await fetchStatus();
      } else {
        showError(res?.message || '操作失败');
      }
    } catch (_) {
      showError('禁用2FA失败');
    } finally {
      loading = false;
    }
  }

  async function handleRegenerateBackupCodes() {
    if (!verificationCode) {
      showWarning('请输入验证码');
      return;
    }
    loading = true;
    try {
      const res = await apiPost('/api/user/2fa/backup_codes', { code: verificationCode });
      if (res?.success) {
        backupCodes = res.data.backup_codes || [];
        showSuccess('备用码重新生成成功');
        verificationCode = '';
        await fetchStatus();
      } else {
        showError(res?.message || '操作失败');
      }
    } catch (_) {
      showError('重新生成备用码失败');
    } finally {
      loading = false;
    }
  }

  /**
   * @param {string} text
   * @param {string} okMsg
   */
  async function copyText(text, okMsg = '已复制到剪贴板') {
    try {
      await navigator.clipboard.writeText(text);
      showSuccess(okMsg);
    } catch (_) {
      showError('复制失败，请手动复制');
    }
  }

  function copyBackupCodes() {
    copyText(backupCodes.join('\n'), '备用码已复制到剪贴板');
  }

  function closeSetup() {
    setupModalVisible = false;
    setupData = null;
    currentStep = 0;
    verificationCode = '';
  }

  onMount(fetchStatus);
</script>

<div class="rounded-xl border border-gray-200 bg-neutral-50 p-4 dark:border-zinc-700 dark:bg-zinc-950/70">
  <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
    <div class="flex gap-4">
      <div
        class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted text-muted-foreground"
      >
        <Shield size={26} weight="duotone" />
      </div>
      <div>
        <div class="mb-1 flex flex-wrap items-center gap-2">
          <span class="font-semibold">两步验证设置</span>
          {#if status.enabled}
            <span class="rounded-full bg-green-500/15 px-2 py-0.5 text-xs text-green-800 dark:text-green-200"
              >已启用</span
            >
          {:else}
            <span class="rounded-full bg-red-500/15 px-2 py-0.5 text-xs text-red-800 dark:text-red-200">未启用</span>
          {/if}
          {#if status.locked}
            <span class="rounded-full bg-amber-500/15 px-2 py-0.5 text-xs text-amber-800 dark:text-amber-200"
              >账户已锁定</span
            >
          {/if}
        </div>
        <p class="text-sm text-muted-foreground">
          两步验证（2FA）为您的账户提供额外的安全保护。启用后，登录时需要输入密码和验证器应用生成的验证码。
        </p>
        {#if status.enabled}
          <p class="mt-2 text-xs text-muted-foreground">
            剩余备用码：{status.backup_codes_remaining || 0} 个
          </p>
        {/if}
      </div>
    </div>
    <div class="flex w-full flex-col gap-2 sm:w-auto">
      {#if !status.enabled}
        <Button class="w-full sm:w-auto" disabled={loading} onclick={handleSetup2FA}>
          <Shield class="mr-1 inline" size={16} />
          启用验证
        </Button>
      {:else}
        <Button variant="destructive" class="w-full sm:w-auto" onclick={() => (disableModalVisible = true)}>
          <Warning class="mr-1 inline" size={16} />
          禁用两步验证
        </Button>
        <Button variant="outline" class="w-full sm:w-auto" onclick={() => (backupModalVisible = true)}>
          <ArrowsClockwise class="mr-1 inline" size={16} />
          重新生成备用码
        </Button>
      {/if}
    </div>
  </div>
</div>

<Dialog.Root bind:open={setupModalVisible}>
  <Dialog.Content class="max-w-lg max-h-[90vh] overflow-y-auto">
    <Dialog.Header>
      <Dialog.Title>设置两步验证</Dialog.Title>
    </Dialog.Header>

    {#if setupData}
      <div class="mb-4 flex gap-2 text-xs">
        {#each ['扫描二维码', '保存备用码', '验证设置'] as label, i}
          <span
            class="rounded-none px-2 py-1 {currentStep === i
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-muted-foreground'}"
            >{i + 1}. {label}</span
          >
        {/each}
      </div>

      {#if currentStep === 0}
        <p class="mb-4 text-sm text-muted-foreground">
          使用认证器应用（如 Google Authenticator、Microsoft Authenticator）扫描下方二维码：
        </p>
        {#if qrDataUrl}
          <div class="mb-4 flex justify-center">
            <div class="rounded-lg bg-white p-3 shadow-sm">
              <img src={qrDataUrl} width="180" height="180" alt="2FA QR" />
            </div>
          </div>
        {/if}
        <div class="rounded-lg bg-blue-500/10 p-3 text-sm">
          <span class="text-blue-900 dark:text-blue-100">或手动输入密钥：</span>
          <code class="ml-2 break-all">{setupData.secret}</code>
          <button
            type="button"
            class="ml-2 text-primary underline"
            onclick={() => copyText(setupData.secret, '密钥已复制')}
          >
            复制
          </button>
        </div>
      {:else if currentStep === 1}
        <div class="space-y-3 rounded-xl border p-3">
          <div class="font-semibold">备用恢复代码</div>
          <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {#each setupData.backup_codes || [] as code, index}
              <div class="rounded-lg bg-muted/50 p-2 font-mono text-sm">
                <div class="flex justify-between">
                  <span>{code}</span>
                  <span class="text-xs text-muted-foreground">#{(index + 1).toString().padStart(2, '0')}</span>
                </div>
              </div>
            {/each}
          </div>
          <Button
            class="w-full"
            variant="secondary"
            onclick={() => copyText((setupData.backup_codes || []).join('\n'), '备用码已复制')}
          >
            <Copy class="mr-1 inline" size={16} />
            复制所有代码
          </Button>
        </div>
      {:else}
        <Input
          placeholder="输入认证器应用显示的6位数字验证码"
          maxlength={6}
          bind:value={verificationCode}
          class="mt-2"
        />
      {/if}

      <Dialog.Footer class="mt-4 flex flex-wrap gap-2">
        {#if currentStep > 0}
          <Button variant="outline" onclick={() => (currentStep -= 1)}>上一步</Button>
        {/if}
        {#if currentStep < 2}
          <Button onclick={() => (currentStep += 1)}>下一步</Button>
        {:else}
          <Button disabled={loading} onclick={handleEnable2FA}>完成设置并启用两步验证</Button>
        {/if}
        <Button variant="ghost" onclick={closeSetup}>关闭</Button>
      </Dialog.Footer>
    {/if}
  </Dialog.Content>
</Dialog.Root>

<Dialog.Root bind:open={disableModalVisible}>
  <Dialog.Content class="max-w-md">
    <Dialog.Header>
      <Dialog.Title>禁用两步验证</Dialog.Title>
    </Dialog.Header>
    <div class="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100">
      警告：禁用两步验证将永久删除您的验证设置和所有备用码，此操作不可撤销！
    </div>
    <label class="auth-label" for="disable-code">验证身份</label>
    <Input id="disable-code" bind:value={verificationCode} placeholder="请输入认证器验证码或备用码" class="mb-3" />
    <label class="flex cursor-pointer items-start gap-2 text-sm">
      <input type="checkbox" bind:checked={confirmDisable} class="mt-1" />
      <span>我已了解禁用两步验证将永久删除所有相关设置和备用码，此操作不可撤销</span>
    </label>
    <Dialog.Footer class="mt-4 gap-2">
      <Button
        variant="outline"
        onclick={() => {
          disableModalVisible = false;
          verificationCode = '';
          confirmDisable = false;
        }}>取消</Button
      >
      <Button variant="destructive" disabled={loading || !confirmDisable || !verificationCode} onclick={handleDisable2FA}
        >确认禁用</Button
      >
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>

<Dialog.Root bind:open={backupModalVisible}>
  <Dialog.Content class="max-w-md">
    <Dialog.Header>
      <Dialog.Title>重新生成备用码</Dialog.Title>
    </Dialog.Header>

    {#if backupCodes.length === 0}
      <div class="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm dark:border-amber-800 dark:bg-amber-950">
        重新生成备用码将使现有的备用码失效，请确保您已保存了当前的备用码。
      </div>
      <label class="auth-label" for="backup-code">验证身份</label>
      <Input id="backup-code" bind:value={verificationCode} placeholder="请输入认证器验证码" />
      <Dialog.Footer class="mt-4 gap-2">
        <Button
          variant="outline"
          onclick={() => {
            backupModalVisible = false;
            verificationCode = '';
            backupCodes = [];
          }}>取消</Button
        >
        <Button disabled={loading || !verificationCode} onclick={handleRegenerateBackupCodes}>生成新的备用码</Button>
      </Dialog.Footer>
    {:else}
      <p class="mb-2 text-sm text-muted-foreground">旧的备用码已失效，请保存新的备用码</p>
      <div class="space-y-2 rounded-xl border p-3">
        {#each backupCodes as code, index}
          <div class="flex justify-between font-mono text-sm">
            <span>{code}</span>
            <span class="text-muted-foreground">#{(index + 1).toString().padStart(2, '0')}</span>
          </div>
        {/each}
      </div>
      <Button class="mt-3 w-full" variant="secondary" onclick={copyBackupCodes}>
        <Copy class="mr-1 inline" size={16} />
        复制所有代码
      </Button>
      <Dialog.Footer class="mt-4">
        <Button
          onclick={() => {
            backupModalVisible = false;
            verificationCode = '';
            backupCodes = [];
          }}>完成</Button
        >
      </Dialog.Footer>
    {/if}
  </Dialog.Content>
</Dialog.Root>

// web/src/components/settings/personal/components/TwoFASetting.jsx
import { API, showError, showSuccess, showWarning } from '../../../../helpers';
import {
  Banner,
  Button,
  Card,
  Checkbox,
  Divider,
  Input,
  Modal,
  Tag,
  Typography,
  Steps,
  Space,
  Badge,
} from '@douyinfe/semi-ui';
import {
  IconShield,
  IconAlertTriangle,
  IconRefresh,
  IconCopy,
} from '@douyinfe/semi-icons';
import React, { useEffect, useState } from 'react';

import { QRCodeSVG } from 'qrcode.react';

const { Text, Paragraph } = Typography;

const TwoFASetting = ({ t }) => {
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState({
    enabled: false,
    locked: false,
    backup_codes_remaining: 0,
  });

  // 模态框状态
  const [setupModalVisible, setSetupModalVisible] = useState(false);
  const [enableModalVisible, setEnableModalVisible] = useState(false);
  const [disableModalVisible, setDisableModalVisible] = useState(false);
  const [backupModalVisible, setBackupModalVisible] = useState(false);

  // 表单数据
  const [setupData, setSetupData] = useState(null);
  const [verificationCode, setVerificationCode] = useState('');
  const [backupCodes, setBackupCodes] = useState([]);
  const [confirmDisable, setConfirmDisable] = useState(false);
  const [currentStep, setCurrentStep] = useState(0);

  // 获取2FA状态
  const fetchStatus = async () => {
    try {
      const res = await API.get('/api/user/2fa/status');
      if (res.data.success) {
        setStatus(res.data.data);
      }
    } catch (error) {
      showError("获取2FA状态失败");
    }
  };

  useEffect(() => {
    fetchStatus();
  }, []);

  // 初始化2FA设置
  const handleSetup2FA = async () => {
    setLoading(true);
    try {
      const res = await API.post('/api/user/2fa/setup');
      if (res.data.success) {
        setSetupData(res.data.data);
        setSetupModalVisible(true);
        setCurrentStep(0);
      } else {
        showError(res.data.message);
      }
    } catch (error) {
      showError("设置2FA失败");
    } finally {
      setLoading(false);
    }
  };

  // 启用2FA
  const handleEnable2FA = async () => {
    if (!verificationCode) {
      showWarning("请输入验证码");
      return;
    }

    setLoading(true);
    try {
      const res = await API.post('/api/user/2fa/enable', {
        code: verificationCode,
      });
      if (res.data.success) {
        showSuccess("两步验证启用成功！");
        setEnableModalVisible(false);
        setSetupModalVisible(false);
        setVerificationCode('');
        setCurrentStep(0);
        fetchStatus();
      } else {
        showError(res.data.message);
      }
    } catch (error) {
      showError("启用2FA失败");
    } finally {
      setLoading(false);
    }
  };

  // 禁用2FA
  const handleDisable2FA = async () => {
    if (!verificationCode) {
      showWarning("请输入验证码或备用码");
      return;
    }

    if (!confirmDisable) {
      showWarning("请确认您已了解禁用两步验证的后果");
      return;
    }

    setLoading(true);
    try {
      const res = await API.post('/api/user/2fa/disable', {
        code: verificationCode,
      });
      if (res.data.success) {
        showSuccess("两步验证已禁用");
        setDisableModalVisible(false);
        setVerificationCode('');
        setConfirmDisable(false);
        fetchStatus();
      } else {
        showError(res.data.message);
      }
    } catch (error) {
      showError("禁用2FA失败");
    } finally {
      setLoading(false);
    }
  };

  // 重新生成备用码
  const handleRegenerateBackupCodes = async () => {
    if (!verificationCode) {
      showWarning("请输入验证码");
      return;
    }

    setLoading(true);
    try {
      const res = await API.post('/api/user/2fa/backup_codes', {
        code: verificationCode,
      });
      if (res.data.success) {
        setBackupCodes(res.data.data.backup_codes);
        showSuccess("备用码重新生成成功");
        setVerificationCode('');
        fetchStatus();
      } else {
        showError(res.data.message);
      }
    } catch (error) {
      showError("重新生成备用码失败");
    } finally {
      setLoading(false);
    }
  };

  // 通用复制函数
  const copyTextToClipboard = (text, successMessage = "已复制到剪贴板") => {
    navigator.clipboard
      .writeText(text)
      .then(() => {
        showSuccess(successMessage);
      })
      .catch(() => {
        showError("复制失败，请手动复制");
      });
  };

  const copyBackupCodes = () => {
    const codesText = backupCodes.join('\n');
    copyTextToClipboard(codesText, "备用码已复制到剪贴板");
  };

  // 备用码展示组件
  const BackupCodesDisplay = ({ codes, title, onCopy }) => {
    return (
      <Card className='!rounded-xl' style={{ width: '100%' }}>
        <div className='space-y-3'>
          <div className='flex items-center justify-between'>
            <Text strong className='text-slate-700 dark:text-slate-200'>
              {title}
            </Text>
          </div>

          <div className='grid grid-cols-1 sm:grid-cols-2 gap-2'>
            {codes.map((code, index) => (
              <div key={index} className='rounded-lg p-3'>
                <div className='flex items-center justify-between'>
                  <Text
                    code
                    className='text-sm font-mono text-slate-700 dark:text-slate-200'
                  >
                    {code}
                  </Text>
                  <Text type='quaternary' className='text-xs'>
                    #{(index + 1).toString().padStart(2, '0')}
                  </Text>
                </div>
              </div>
            ))}
          </div>

          <Divider margin={12} />
          <Button
            type='primary'
            theme='solid'
            icon={<IconCopy />}
            onClick={onCopy}
            className='!rounded-lg !bg-slate-600 hover:!bg-slate-700 w-full'
          >
            {"复制所有代码"}
          </Button>
        </div>
      </Card>
    );
  };

  // 渲染设置模态框footer
  const renderSetupModalFooter = () => {
    return (
      <>
        {currentStep > 0 && (
          <Button
            onClick={() => setCurrentStep(currentStep - 1)}
            className='!rounded-lg'
          >
            {"上一步"}
          </Button>
        )}
        {currentStep < 2 ? (
          <Button
            type='primary'
            theme='solid'
            onClick={() => setCurrentStep(currentStep + 1)}
            className='!rounded-lg !bg-slate-600 hover:!bg-slate-700'
          >
            {"下一步"}
          </Button>
        ) : (
          <Button
            type='primary'
            theme='solid'
            loading={loading}
            onClick={() => {
              if (!verificationCode) {
                showWarning("请输入验证码");
                return;
              }
              handleEnable2FA();
            }}
            className='!rounded-lg !bg-slate-600 hover:!bg-slate-700'
          >
            {"完成设置并启用两步验证"}
          </Button>
        )}
      </>
    );
  };

  // 渲染禁用模态框footer
  const renderDisableModalFooter = () => {
    return (
      <>
        <Button
          onClick={() => {
            setDisableModalVisible(false);
            setVerificationCode('');
            setConfirmDisable(false);
          }}
          className='!rounded-lg'
        >
          {"取消"}
        </Button>
        <Button
          type='danger'
          theme='solid'
          loading={loading}
          disabled={!confirmDisable || !verificationCode}
          onClick={handleDisable2FA}
          className='!rounded-lg !bg-slate-500 hover:!bg-slate-600'
        >
          {"确认禁用"}
        </Button>
      </>
    );
  };

  // 渲染重新生成模态框footer
  const renderRegenerateModalFooter = () => {
    if (backupCodes.length > 0) {
      return (
        <Button
          type='primary'
          theme='solid'
          onClick={() => {
            setBackupModalVisible(false);
            setVerificationCode('');
            setBackupCodes([]);
          }}
          className='!rounded-lg !bg-slate-600 hover:!bg-slate-700'
        >
          {"完成"}
        </Button>
      );
    }

    return (
      <>
        <Button
          onClick={() => {
            setBackupModalVisible(false);
            setVerificationCode('');
            setBackupCodes([]);
          }}
          className='!rounded-lg'
        >
          {"取消"}
        </Button>
        <Button
          type='primary'
          theme='solid'
          loading={loading}
          disabled={!verificationCode}
          onClick={handleRegenerateBackupCodes}
          className='!rounded-lg !bg-slate-600 hover:!bg-slate-700'
        >
          {"生成新的备用码"}
        </Button>
      </>
    );
  };

  return (
    <>
      <Card className='!rounded-xl w-full'>
        <div className='flex flex-col sm:flex-row items-start sm:justify-between gap-4'>
          <div className='flex items-start w-full sm:w-auto'>
            <div className='w-12 h-12 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-4 flex-shrink-0'>
              <IconShield
                size='large'
                className='text-slate-600 dark:text-slate-300'
              />
            </div>
            <div className='flex-1'>
              <div className='flex items-center gap-2 mb-1'>
                <Typography.Title heading={6} className='mb-0'>
                  {"两步验证设置"}
                </Typography.Title>
                {status.enabled ? (
                  <Tag color='green' shape='circle' size='small'>
                    {"已启用"}
                  </Tag>
                ) : (
                  <Tag color='red' shape='circle' size='small'>
                    {"未启用"}
                  </Tag>
                )}
                {status.locked && (
                  <Tag color='orange' shape='circle' size='small'>
                    {"账户已锁定"}
                  </Tag>
                )}
              </div>
              <Typography.Text type='tertiary' className='text-sm'>
                {"两步验证（2FA）为您的账户提供额外的安全保护。启用后，登录时需要输入密码和验证器应用生成的验证码。"}
              </Typography.Text>
              {status.enabled && (
                <div className='mt-2'>
                  <Text size='small' type='secondary'>
                    {"剩余备用码："}
                    {status.backup_codes_remaining || 0}
                    {"个"}
                  </Text>
                </div>
              )}
            </div>
          </div>
          <div className='flex flex-col space-y-2 w-full sm:w-auto'>
            {!status.enabled ? (
              <Button
                type='primary'
                theme='solid'
                size='default'
                onClick={handleSetup2FA}
                loading={loading}
                className='!rounded-lg !bg-slate-600 hover:!bg-slate-700'
                icon={<IconShield />}
              >
                {"启用验证"}
              </Button>
            ) : (
              <div className='flex flex-col space-y-2'>
                <Button
                  type='danger'
                  theme='solid'
                  size='default'
                  onClick={() => setDisableModalVisible(true)}
                  className='!rounded-lg !bg-slate-500 hover:!bg-slate-600'
                  icon={<IconAlertTriangle />}
                >
                  {"禁用两步验证"}
                </Button>
                <Button
                  type='primary'
                  theme='solid'
                  size='default'
                  onClick={() => setBackupModalVisible(true)}
                  className='!rounded-lg'
                  icon={<IconRefresh />}
                >
                  {"重新生成备用码"}
                </Button>
              </div>
            )}
          </div>
        </div>
      </Card>

      {/* 2FA设置模态框 */}
      <Modal
        title={
          <div className='flex items-center'>
            <IconShield className='mr-2 text-slate-600' />
            {"设置两步验证"}
          </div>
        }
        visible={setupModalVisible}
        onCancel={() => {
          setSetupModalVisible(false);
          setSetupData(null);
          setCurrentStep(0);
          setVerificationCode('');
        }}
        footer={renderSetupModalFooter()}
        width={650}
        style={{ maxWidth: '90vw' }}
      >
        {setupData && (
          <div className='space-y-6'>
            {/* 步骤进度 */}
            <Steps type='basic' size='small' current={currentStep}>
              <Steps.Step
                title={"扫描二维码"}
                description={"使用认证器应用扫描二维码"}
              />
              <Steps.Step
                title={"保存备用码"}
                description={"保存备用码以备不时之需"}
              />
              <Steps.Step
                title={"验证设置"}
                description={"输入验证码完成设置"}
              />
            </Steps>

            {/* 步骤内容 */}
            <div className='rounded-xl'>
              {currentStep === 0 && (
                <div>
                  <Paragraph className='text-gray-600 dark:text-gray-300 mb-4'>
                    {"使用认证器应用（如 Google Authenticator、Microsoft Authenticator）扫描下方二维码："}
                  </Paragraph>
                  <div className='flex justify-center mb-4'>
                    <div className='bg-white p-4 rounded-lg shadow-sm'>
                      <QRCodeSVG value={setupData.qr_code_data} size={180} />
                    </div>
                  </div>
                  <div className='bg-blue-50 dark:bg-blue-900 rounded-lg p-3'>
                    <Text className='text-blue-800 dark:text-blue-200 text-sm'>
                      {"或手动输入密钥："}
                      <Text code copyable className='ml-2'>
                        {setupData.secret}
                      </Text>
                    </Text>
                  </div>
                </div>
              )}

              {currentStep === 1 && (
                <div className='space-y-4'>
                  {/* 备用码展示 */}
                  <BackupCodesDisplay
                    codes={setupData.backup_codes}
                    title={"备用恢复代码"}
                    onCopy={() => {
                      const codesText = setupData.backup_codes.join('\n');
                      copyTextToClipboard(codesText, "备用码已复制到剪贴板");
                    }}
                  />
                </div>
              )}

              {currentStep === 2 && (
                <Input
                  placeholder={"输入认证器应用显示的6位数字验证码"}
                  value={verificationCode}
                  onChange={setVerificationCode}
                  size='large'
                  maxLength={6}
                  className='!rounded-lg'
                />
              )}
            </div>
          </div>
        )}
      </Modal>

      {/* 禁用2FA模态框 */}
      <Modal
        title={
          <div className='flex items-center'>
            <IconAlertTriangle className='mr-2 text-red-500' />
            {"禁用两步验证"}
          </div>
        }
        visible={disableModalVisible}
        onCancel={() => {
          setDisableModalVisible(false);
          setVerificationCode('');
          setConfirmDisable(false);
        }}
        footer={renderDisableModalFooter()}
        width={550}
        style={{ maxWidth: '90vw' }}
      >
        <div className='space-y-6'>
          {/* 警告提示 */}
          <div className='rounded-xl'>
            <Banner
              type='warning'
              description={"警告：禁用两步验证将永久删除您的验证设置和所有备用码，此操作不可撤销！"}
              className='!rounded-lg'
            />
          </div>

          {/* 内容区域 */}
          <div className='space-y-4'>
            <div>
              <Text
                strong
                className='block mb-2 text-slate-700 dark:text-slate-200'
              >
                {"禁用后的影响："}
              </Text>
              <ul className='space-y-2 text-sm text-slate-600 dark:text-slate-300'>
                <li className='flex items-start gap-2'>
                  <Badge dot type='warning' />
                  {"降低您账户的安全性"}
                </li>
                <li className='flex items-start gap-2'>
                  <Badge dot type='warning' />
                  {"需要重新完整设置才能再次启用"}
                </li>
                <li className='flex items-start gap-2'>
                  <Badge dot type='danger' />
                  {"永久删除您的两步验证设置"}
                </li>
                <li className='flex items-start gap-2'>
                  <Badge dot type='danger' />
                  {"永久删除所有备用码（包括未使用的）"}
                </li>
              </ul>
            </div>

            <Divider margin={16} />

            <div className='space-y-4'>
              <div>
                <Text
                  strong
                  className='block mb-2 text-slate-700 dark:text-slate-200'
                >
                  {"验证身份"}
                </Text>
                <Input
                  placeholder={"请输入认证器验证码或备用码"}
                  value={verificationCode}
                  onChange={setVerificationCode}
                  size='large'
                  className='!rounded-lg'
                />
              </div>

              <div>
                <Checkbox
                  checked={confirmDisable}
                  onChange={(e) => setConfirmDisable(e.target.checked)}
                  className='text-sm'
                >
                  {"我已了解禁用两步验证将永久删除所有相关设置和备用码，此操作不可撤销"}
                </Checkbox>
              </div>
            </div>
          </div>
        </div>
      </Modal>

      {/* 重新生成备用码模态框 */}
      <Modal
        title={
          <div className='flex items-center'>
            <IconRefresh className='mr-2 text-slate-600' />
            {"重新生成备用码"}
          </div>
        }
        visible={backupModalVisible}
        onCancel={() => {
          setBackupModalVisible(false);
          setVerificationCode('');
          setBackupCodes([]);
        }}
        footer={renderRegenerateModalFooter()}
        width={500}
        style={{ maxWidth: '90vw' }}
      >
        <div className='space-y-6'>
          {backupCodes.length === 0 ? (
            <>
              {/* 警告提示 */}
              <div className='rounded-xl'>
                <Banner
                  type='warning'
                  description={"重新生成备用码将使现有的备用码失效，请确保您已保存了当前的备用码。"}
                  className='!rounded-lg'
                />
              </div>

              {/* 验证区域 */}
              <div className='space-y-4'>
                <div>
                  <Text
                    strong
                    className='block mb-2 text-slate-700 dark:text-slate-200'
                  >
                    {"验证身份"}
                  </Text>
                  <Input
                    placeholder={"请输入认证器验证码"}
                    value={verificationCode}
                    onChange={setVerificationCode}
                    size='large'
                    className='!rounded-lg'
                  />
                </div>
              </div>
            </>
          ) : (
            <>
              {/* 成功提示 */}
              <Space vertical style={{ width: '100%' }}>
                <div className='flex items-center justify-center gap-2'>
                  <Badge dot type='success' />
                  <Text
                    strong
                    className='text-lg text-slate-700 dark:text-slate-200'
                  >
                    {"新的备用码已生成"}
                  </Text>
                </div>
                <Text className='text-slate-500 dark:text-slate-400 text-sm'>
                  {"旧的备用码已失效，请保存新的备用码"}
                </Text>

                {/* 备用码展示 */}
                <BackupCodesDisplay
                  codes={backupCodes}
                  title={"新的备用恢复代码"}
                  onCopy={copyBackupCodes}
                />
              </Space>
            </>
          )}
        </div>
      </Modal>
    </>
  );
};

export default TwoFASetting;
