// web/src/lib/components/dashboard/AccountManagement.svelte
<svelte:options runes={false} />

<script>
  import { onMount } from 'svelte';
  import { apiDelete, apiGet } from '$lib/api';
  import { showError, showSuccess } from '$lib/dashboard/notify.js';
  import {
    onGitHubOAuthClicked,
    onDiscordOAuthClicked,
    onOIDCClicked,
    onLinuxDOOAuthClicked,
    onCustomOAuthClicked,
  } from '$lib/dashboard/oauth.js';
  import { Button } from '$lib/components/ui/button';
  import * as Dialog from '$lib/components/ui/dialog';
  import * as AlertDialog from '$lib/components/ui/alert-dialog';
  import {
    EnvelopeSimple,
    GithubLogo,
    Shield,
    Key,
    Lock,
    Trash,
  } from 'phosphor-svelte';
  import TwoFASetting from './TwoFASetting.svelte';
  import TelegramLoginWidget from './TelegramLoginWidget.svelte';

  /** @type {{ user?: Record<string, any> } | null} */
  export let userState = { user: null };
  /** @type {Record<string, any>} */
  export let status = {};
  export let systemToken = '';

  /** @type {{ enabled?: boolean; last_used_at?: string | null }} */
  export let passkeyStatus = { enabled: false };
  export let passkeySupported = false;
  export let passkeyRegisterLoading = false;
  export let passkeyDeleteLoading = false;

  export let onGenerateAccessToken = () => {};
  /** @param {MouseEvent} e */
  export let onSystemTokenClick = (e) => {};
  export let onPasskeyRegister = () => {};
  export let onPasskeyDelete = () => {};
  export let onOpenEmailBind = () => {};
  export let onOpenWeChatBind = () => {};
  export let onOpenChangePassword = () => {};
  export let onOpenDeleteAccount = () => {};

  /** @type {'binding' | 'security'} */
  export let section = 'binding';

  let showTelegramModal = false;
  /** @type {any[]} */
  let customOAuthBindings = [];
  /** @type {Record<string, boolean>} */
  let customOAuthLoading = {};

  let showUnbindOAuthDialog = false;
  /** @type {{ providerId: number | string; providerName: string } | null} */
  let unbindOAuthPending = null;

  let showPasskeyUnbindConfirm = false;

  async function loadCustomOAuthBindings() {
    try {
      const res = await apiGet('/api/user/oauth/bindings');
      if (res?.success) {
        customOAuthBindings = res.data || [];
      } else {
        showError(res?.message || '获取绑定信息失败');
      }
    } catch (err) {
      showError(err?.message || '获取绑定信息失败');
    }
  }

  onMount(loadCustomOAuthBindings);

  /**
   * @param {string | undefined} id
   */
  function isBound(id) {
    return Boolean(id);
  }

  /**
   * @param {string} accountId
   * @param {string} [label]
   */
  function accountLine(accountId, label) {
    if (!accountId) return '未绑定';
    return accountId;
  }

  /**
   * @param {number|string} providerId
   */
  function isCustomOAuthBound(providerId) {
    const normalizedId = Number(providerId);
    return customOAuthBindings.some((b) => Number(b.provider_id) === normalizedId);
  }

  /**
   * @param {number|string} providerId
   */
  function getCustomOAuthBinding(providerId) {
    const normalizedId = Number(providerId);
    return customOAuthBindings.find((b) => Number(b.provider_id) === normalizedId);
  }

  /**
   * @param {number|string} providerId
   * @param {string} providerName
   */
  function requestUnbindCustomOAuth(providerId, providerName) {
    unbindOAuthPending = { providerId, providerName };
    showUnbindOAuthDialog = true;
  }

  async function confirmUnbindCustomOAuth() {
    if (!unbindOAuthPending) return;
    const { providerId } = unbindOAuthPending;
    const providerKey = String(providerId);
    customOAuthLoading = { ...customOAuthLoading, [providerKey]: true };
    try {
      const res = await apiDelete(`/api/user/oauth/bindings/${providerId}`);
      if (res?.success) {
        showSuccess('解绑成功');
        await loadCustomOAuthBindings();
      } else {
        showError(res?.message || '操作失败');
      }
    } catch (err) {
      showError(err?.message || '操作失败');
    } finally {
      const next = { ...customOAuthLoading };
      delete next[providerKey];
      customOAuthLoading = next;
      showUnbindOAuthDialog = false;
      unbindOAuthPending = null;
    }
  }

  /**
   * @param {string} icon
   * @param {string} name
   */
  function oauthIcon(icon, name) {
    const raw = String(icon || '').trim();
    if (raw.startsWith('http://') || raw.startsWith('https://')) {
      return { type: 'img', src: raw, alt: '' };
    }
    if (raw && /[\u{1F300}-\u{1FAFF}]/u.test(raw)) {
      return { type: 'emoji', text: raw };
    }
    return { type: 'letter', text: (name || '?').charAt(0).toUpperCase() };
  }

  $: passkeyEnabled = passkeyStatus?.enabled;
  $: lastUsedLabel = passkeyStatus?.last_used_at
    ? new Date(passkeyStatus.last_used_at).toLocaleString()
    : '尚未使用';
</script>

<div class="w-full min-w-0">
  {#if section === 'binding'}
    <div class="grid grid-cols-1 gap-4 lg:grid-cols-2">
      <!-- 邮箱 -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted">
              <EnvelopeSimple size={20} />
            </div>
            <div class="min-w-0">
              <div class="font-medium">邮箱</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.email || ''}>
                {accountLine(userState?.user?.email)}
              </div>
            </div>
          </div>
          <Button variant="outline" size="sm" onclick={onOpenEmailBind}>
            {isBound(userState?.user?.email) ? '修改绑定' : '绑定'}
          </Button>
        </div>
      </div>

      <!-- 微信 -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted text-lg">💬</div>
            <div class="min-w-0">
              <div class="font-medium">微信</div>
              <div class="truncate text-sm text-muted-foreground">
                {#if !status.wechat_login}
                  未启用
                {:else if isBound(userState?.user?.wechat_id)}
                  已绑定
                {:else}
                  未绑定
                {/if}
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={!status.wechat_login}
            onclick={onOpenWeChatBind}
          >
            {isBound(userState?.user?.wechat_id)
              ? '修改绑定'
              : status.wechat_login
                ? '绑定'
                : '未启用'}
          </Button>
        </div>
      </div>

      <!-- GitHub -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted">
              <GithubLogo size={20} />
            </div>
            <div class="min-w-0">
              <div class="font-medium">GitHub</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.github_id || ''}>
                {accountLine(userState?.user?.github_id)}
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={isBound(userState?.user?.github_id) || !status.github_oauth}
            onclick={() => onGitHubOAuthClicked(status.github_client_id)}
          >
            {status.github_oauth ? '绑定' : '未启用'}
          </Button>
        </div>
      </div>

      <!-- Discord -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted text-sm font-bold">D</div>
            <div class="min-w-0">
              <div class="font-medium">Discord</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.discord_id || ''}>
                {accountLine(userState?.user?.discord_id)}
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={isBound(userState?.user?.discord_id) || !status.discord_oauth}
            onclick={() => onDiscordOAuthClicked(status.discord_client_id)}
          >
            {status.discord_oauth ? '绑定' : '未启用'}
          </Button>
        </div>
      </div>

      <!-- OIDC -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted">
              <Shield size={20} />
            </div>
            <div class="min-w-0">
              <div class="font-medium">OIDC</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.oidc_id || ''}>
                {accountLine(userState?.user?.oidc_id)}
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={isBound(userState?.user?.oidc_id) || !status.oidc_enabled}
            onclick={() => onOIDCClicked(status.oidc_authorization_endpoint, status.oidc_client_id)}
          >
            {status.oidc_enabled ? '绑定' : '未启用'}
          </Button>
        </div>
      </div>

      <!-- Telegram -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted text-lg">✈</div>
            <div class="min-w-0">
              <div class="font-medium">Telegram</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.telegram_id || ''}>
                {accountLine(userState?.user?.telegram_id)}
              </div>
            </div>
          </div>
          <div class="shrink-0">
            {#if status.telegram_oauth}
              {#if isBound(userState?.user?.telegram_id)}
                <Button variant="outline" size="sm" disabled>已绑定</Button>
              {:else}
                <Button variant="outline" size="sm" onclick={() => (showTelegramModal = true)}>绑定</Button>
              {/if}
            {:else}
              <Button variant="outline" size="sm" disabled>未启用</Button>
            {/if}
          </div>
        </div>
      </div>

      <!-- LinuxDO -->
      <div class="rounded-xl border border-border p-4">
        <div class="flex items-center justify-between gap-3">
          <div class="flex min-w-0 flex-1 items-center gap-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold">L</div>
            <div class="min-w-0">
              <div class="font-medium">LinuxDO</div>
              <div class="truncate text-sm text-muted-foreground" title={userState?.user?.linux_do_id || ''}>
                {accountLine(userState?.user?.linux_do_id)}
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            disabled={isBound(userState?.user?.linux_do_id) || !status.linuxdo_oauth}
            onclick={() => onLinuxDOOAuthClicked(status.linuxdo_client_id)}
          >
            {status.linuxdo_oauth ? '绑定' : '未启用'}
          </Button>
        </div>
      </div>

      {#if status.custom_oauth_providers}
        {#each status.custom_oauth_providers as provider}
          {@const bound = isCustomOAuthBound(provider.id)}
          {@const binding = getCustomOAuthBinding(provider.id)}
          {@const icon = oauthIcon(provider.icon || binding?.provider_icon || '', provider.name)}
          <div class="rounded-xl border border-border p-4">
            <div class="flex items-center justify-between gap-3">
              <div class="flex min-w-0 flex-1 items-center gap-3">
                <div class="flex h-10 w-10 shrink-0 items-center justify-center overflow-hidden rounded-full bg-muted">
                  {#if icon.type === 'img'}
                    <img src={icon.src} alt="" class="h-8 w-8 rounded object-cover" />
                  {:else if icon.type === 'emoji'}
                    <span class="text-lg">{icon.text}</span>
                  {:else}
                    <span class="text-sm font-medium">{icon.text}</span>
                  {/if}
                </div>
                <div class="min-w-0">
                  <div class="font-medium">{provider.name}</div>
                  <div class="truncate text-sm text-muted-foreground">
                    {#if bound}
                      {binding?.provider_user_id || ''}
                    {:else}
                      未绑定
                    {/if}
                  </div>
                </div>
              </div>
              <div class="shrink-0">
                {#if bound}
                  <Button
                    variant="destructive"
                    size="sm"
                    disabled={customOAuthLoading[String(provider.id)]}
                    onclick={() => requestUnbindCustomOAuth(provider.id, provider.name)}
                  >
                    解绑
                  </Button>
                {:else}
                  <Button variant="outline" size="sm" onclick={() => onCustomOAuthClicked(provider)}>绑定</Button>
                {/if}
              </div>
            </div>
          </div>
        {/each}
      {/if}
    </div>
  {:else}
    <div class="space-y-6">
      <div class="rounded-xl border border-border p-4">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div class="flex gap-4">
            <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted">
              <Key size={24} />
            </div>
            <div>
              <div class="mb-1 font-semibold">系统访问令牌</div>
              <p class="text-sm text-muted-foreground">用于API调用的身份验证令牌，请妥善保管</p>
              {#if systemToken}
                <input
                  readonly
                  class="auth-input mt-3 w-full max-w-md cursor-pointer font-mono text-xs"
                  value={systemToken}
                  on:click={onSystemTokenClick}
                />
              {/if}
            </div>
          </div>
          <Button variant="secondary" class="self-start" onclick={onGenerateAccessToken}>
            <Key class="mr-1 inline" size={16} />
            {systemToken ? '重新生成' : '生成令牌'}
          </Button>
        </div>
      </div>

      <div class="rounded-xl border border-border p-4">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div class="flex gap-4">
            <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted">
              <Lock size={24} />
            </div>
            <div>
              <div class="mb-1 font-semibold">密码管理</div>
              <p class="text-sm text-muted-foreground">定期更改密码可以提高账户安全性</p>
            </div>
          </div>
          <Button variant="secondary" class="self-start" onclick={onOpenChangePassword}>
            <Lock class="mr-1 inline" size={16} />
            修改密码
          </Button>
        </div>
      </div>

      <div class="rounded-xl border border-border p-4">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div class="flex gap-4">
            <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted">
              <Key size={24} />
            </div>
            <div>
              <div class="mb-1 font-semibold">Passkey 登录</div>
              <p class="text-sm text-muted-foreground">
                {passkeyEnabled
                  ? '已启用 Passkey，无需密码即可登录'
                  : '使用 Passkey 实现免密且更安全的登录体验'}
              </p>
              <div class="mt-2 space-y-1 text-xs text-muted-foreground">
                <div>最后使用时间：{lastUsedLabel}</div>
                {#if !passkeySupported}
                  <div class="text-amber-600">当前设备不支持 Passkey</div>
                {/if}
              </div>
            </div>
          </div>
          <Button
            variant={passkeyEnabled ? 'destructive' : 'default'}
            class="self-start"
            disabled={
              (!passkeySupported && !passkeyEnabled) ||
              (passkeyEnabled ? passkeyDeleteLoading : passkeyRegisterLoading)
            }
            onclick={() => {
              if (passkeyEnabled) {
                showPasskeyUnbindConfirm = true;
              } else {
                onPasskeyRegister();
              }
            }}
          >
            {(passkeyEnabled ? passkeyDeleteLoading : passkeyRegisterLoading)
              ? '请稍候...'
              : passkeyEnabled
                ? '解绑 Passkey'
                : '注册 Passkey'}
          </Button>
        </div>
      </div>

      <TwoFASetting />

      <div class="rounded-xl border border-border p-4">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div class="flex gap-4">
            <div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-muted">
              <Trash size={24} />
            </div>
            <div>
              <div class="mb-1 font-semibold">删除账户</div>
              <p class="text-sm text-muted-foreground">此操作不可逆，所有数据将被永久删除</p>
            </div>
          </div>
          <Button variant="destructive" class="self-start" onclick={onOpenDeleteAccount}>
            <Trash class="mr-1 inline" size={16} />
            删除账户
          </Button>
        </div>
      </div>
    </div>
  {/if}
</div>

<AlertDialog.Root
  bind:open={showUnbindOAuthDialog}
  onOpenChange={(/** @type {boolean} */ open) => {
    if (!open) unbindOAuthPending = null;
  }}
>
  <AlertDialog.Content class="max-w-md">
    <AlertDialog.Header>
      <AlertDialog.Title>确认解绑</AlertDialog.Title>
      <AlertDialog.Description>
        确定要解绑 {unbindOAuthPending?.providerName ?? ''} 吗？
      </AlertDialog.Description>
    </AlertDialog.Header>
    <AlertDialog.Footer class="gap-2">
      <AlertDialog.Cancel>取消</AlertDialog.Cancel>
      <AlertDialog.Action onclick={confirmUnbindCustomOAuth}>确认</AlertDialog.Action>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>

<AlertDialog.Root bind:open={showPasskeyUnbindConfirm}>
  <AlertDialog.Content class="max-w-md">
    <AlertDialog.Header>
      <AlertDialog.Title>解绑 Passkey</AlertDialog.Title>
      <AlertDialog.Description>解绑后将无法使用 Passkey 登录，确定要继续吗？</AlertDialog.Description>
    </AlertDialog.Header>
    <AlertDialog.Footer class="gap-2">
      <AlertDialog.Cancel>取消</AlertDialog.Cancel>
      <AlertDialog.Action
        variant="destructive"
        onclick={() => {
          onPasskeyDelete();
          showPasskeyUnbindConfirm = false;
        }}
      >
        解绑
      </AlertDialog.Action>
    </AlertDialog.Footer>
  </AlertDialog.Content>
</AlertDialog.Root>

<Dialog.Root bind:open={showTelegramModal}>
  <Dialog.Content class="max-w-sm">
    <Dialog.Header>
      <Dialog.Title>绑定 Telegram</Dialog.Title>
    </Dialog.Header>
    <p class="text-sm text-muted-foreground">点击下方按钮通过 Telegram 完成绑定</p>
    <div class="scale-95">
      <TelegramLoginWidget
        botName={status.telegram_bot_name}
        authUrl={`${typeof window !== 'undefined' ? window.location.origin : ''}/api/oauth/telegram/bind`}
      />
    </div>
  </Dialog.Content>
</Dialog.Root>

// web/src/components/settings/personal/cards/AccountManagement.jsx
import React from 'react';
import {
  Button,
  Card,
  Input,
  Space,
  Typography,
  Avatar,
  Tabs,
  TabPane,
  Popover,
  Modal,
} from '@douyinfe/semi-ui';
import {
  IconMail,
  IconShield,
  IconGithubLogo,
  IconKey,
  IconLock,
  IconDelete,
} from '@douyinfe/semi-icons';
import { SiTelegram, SiWechat, SiLinux, SiDiscord } from 'react-icons/si';
import { UserPlus, ShieldCheck } from 'lucide-react';
import TelegramLoginButton from 'react-telegram-login';
import {
  API,
  showError,
  showSuccess,
  onGitHubOAuthClicked,
  onOIDCClicked,
  onLinuxDOOAuthClicked,
  onDiscordOAuthClicked,
  onCustomOAuthClicked,
  getOAuthProviderIcon,
} from '../../../../helpers';
import TwoFASetting from '../components/TwoFASetting';

const AccountManagement = ({
  t,
  userState,
  status,
  systemToken,
  setShowEmailBindModal,
  setShowWeChatBindModal,
  generateAccessToken,
  handleSystemTokenClick,
  setShowChangePasswordModal,
  setShowAccountDeleteModal,
  passkeyStatus,
  passkeySupported,
  passkeyRegisterLoading,
  passkeyDeleteLoading,
  onPasskeyRegister,
  onPasskeyDelete,
}) => {
  const renderAccountInfo = (accountId, label) => {
    if (!accountId || accountId === '') {
      return <span className='text-gray-500'>{t('未绑定')}</span>;
    }

    const popContent = (
      <div className='text-xs p-2'>
        <Typography.Paragraph copyable={{ content: accountId }}>
          {accountId}
        </Typography.Paragraph>
        {label ? (
          <div className='mt-1 text-[11px] text-gray-500'>{label}</div>
        ) : null}
      </div>
    );

    return (
      <Popover content={popContent} position='top' trigger='hover'>
        <span className='block max-w-full truncate text-gray-600 hover:text-blue-600 cursor-pointer'>
          {accountId}
        </span>
      </Popover>
    );
  };
  const isBound = (accountId) => Boolean(accountId);
  const [showTelegramBindModal, setShowTelegramBindModal] =
    React.useState(false);
  const [customOAuthBindings, setCustomOAuthBindings] = React.useState([]);
  const [customOAuthLoading, setCustomOAuthLoading] = React.useState({});

  // Fetch custom OAuth bindings
  const loadCustomOAuthBindings = async () => {
    try {
      const res = await API.get('/api/user/oauth/bindings');
      if (res.data.success) {
        setCustomOAuthBindings(res.data.data || []);
      } else {
        showError(res.data.message || t('获取绑定信息失败'));
      }
    } catch (error) {
      showError(error.response?.data?.message || error.message || t('获取绑定信息失败'));
    }
  };

  // Unbind custom OAuth provider
  const handleUnbindCustomOAuth = async (providerId, providerName) => {
    Modal.confirm({
      title: t('确认解绑'),
      content: t('确定要解绑 {{name}} 吗？', { name: providerName }),
      okText: t('确认'),
      cancelText: t('取消'),
      onOk: async () => {
        setCustomOAuthLoading((prev) => ({ ...prev, [providerId]: true }));
        try {
          const res = await API.delete(`/api/user/oauth/bindings/${providerId}`);
          if (res.data.success) {
            showSuccess(t('解绑成功'));
            await loadCustomOAuthBindings();
          } else {
            showError(res.data.message);
          }
        } catch (error) {
          showError(error.response?.data?.message || error.message || t('操作失败'));
        } finally {
          setCustomOAuthLoading((prev) => ({ ...prev, [providerId]: false }));
        }
      },
    });
  };

  // Handle bind custom OAuth
  const handleBindCustomOAuth = (provider) => {
    onCustomOAuthClicked(provider);
  };

  // Check if custom OAuth provider is bound
  const isCustomOAuthBound = (providerId) => {
    const normalizedId = Number(providerId);
    return customOAuthBindings.some((b) => Number(b.provider_id) === normalizedId);
  };

  // Get binding info for a provider
  const getCustomOAuthBinding = (providerId) => {
    const normalizedId = Number(providerId);
    return customOAuthBindings.find((b) => Number(b.provider_id) === normalizedId);
  };

  React.useEffect(() => {
    loadCustomOAuthBindings();
  }, []);

  const passkeyEnabled = passkeyStatus?.enabled;
  const lastUsedLabel = passkeyStatus?.last_used_at
    ? new Date(passkeyStatus.last_used_at).toLocaleString()
    : t('尚未使用');

  return (
    <Card className='!rounded-2xl'>
      {/* 卡片头部 */}
      <div className='flex items-center mb-4'>
        <Avatar size='small' color='teal' className='mr-3 shadow-md'>
          <UserPlus size={16} />
        </Avatar>
        <div>
          <Typography.Text className='text-lg font-medium'>
            {t('账户管理')}
          </Typography.Text>
          <div className='text-xs text-gray-600'>
            {t('账户绑定、安全设置和身份验证')}
          </div>
        </div>
      </div>

      <Tabs type='card' defaultActiveKey='binding'>
        {/* 账户绑定 Tab */}
        <TabPane
          tab={
            <div className='flex items-center'>
              <UserPlus size={16} className='mr-2' />
              {t('账户绑定')}
            </div>
          }
          itemKey='binding'
        >
          <div className='py-4'>
            <div className='grid grid-cols-1 lg:grid-cols-2 gap-4'>
              {/* 邮箱绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <IconMail
                        size='default'
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('邮箱')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.email,
                          t('邮箱地址'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      onClick={() => setShowEmailBindModal(true)}
                    >
                      {isBound(userState.user?.email)
                        ? t('修改绑定')
                        : t('绑定')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* 微信绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <SiWechat
                        size={20}
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('微信')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {!status.wechat_login
                          ? t('未启用')
                          : isBound(userState.user?.wechat_id)
                            ? t('已绑定')
                            : t('未绑定')}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      disabled={!status.wechat_login}
                      onClick={() => setShowWeChatBindModal(true)}
                    >
                      {isBound(userState.user?.wechat_id)
                        ? t('修改绑定')
                        : status.wechat_login
                          ? t('绑定')
                          : t('未启用')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* GitHub绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <IconGithubLogo
                        size='default'
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('GitHub')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.github_id,
                          t('GitHub ID'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      onClick={() =>
                        onGitHubOAuthClicked(status.github_client_id)
                      }
                      disabled={
                        isBound(userState.user?.github_id) ||
                        !status.github_oauth
                      }
                    >
                      {status.github_oauth ? t('绑定') : t('未启用')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* Discord绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <SiDiscord
                        size={20}
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('Discord')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.discord_id,
                          t('Discord ID'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      onClick={() =>
                        onDiscordOAuthClicked(status.discord_client_id)
                      }
                      disabled={
                        isBound(userState.user?.discord_id) ||
                        !status.discord_oauth
                      }
                    >
                      {status.discord_oauth ? t('绑定') : t('未启用')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* OIDC绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <IconShield
                        size='default'
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('OIDC')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.oidc_id,
                          t('OIDC ID'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      onClick={() =>
                        onOIDCClicked(
                          status.oidc_authorization_endpoint,
                          status.oidc_client_id,
                        )
                      }
                      disabled={
                        isBound(userState.user?.oidc_id) || !status.oidc_enabled
                      }
                    >
                      {status.oidc_enabled ? t('绑定') : t('未启用')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* Telegram绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <SiTelegram
                        size={20}
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('Telegram')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.telegram_id,
                          t('Telegram ID'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    {status.telegram_oauth ? (
                      isBound(userState.user?.telegram_id) ? (
                        <Button
                          disabled
                          size='small'
                          type='primary'
                          theme='outline'
                        >
                          {t('已绑定')}
                        </Button>
                      ) : (
                        <Button
                          type='primary'
                          theme='outline'
                          size='small'
                          onClick={() => setShowTelegramBindModal(true)}
                        >
                          {t('绑定')}
                        </Button>
                      )
                    ) : (
                      <Button
                        disabled
                        size='small'
                        type='primary'
                        theme='outline'
                      >
                        {t('未启用')}
                      </Button>
                    )}
                  </div>
                </div>
              </Card>
              <Modal
                title={t('绑定 Telegram')}
                visible={showTelegramBindModal}
                onCancel={() => setShowTelegramBindModal(false)}
                footer={null}
              >
                <div className='my-3 text-sm text-gray-600'>
                  {t('点击下方按钮通过 Telegram 完成绑定')}
                </div>
                <div className='flex justify-center'>
                  <div className='scale-90'>
                    <TelegramLoginButton
                      dataAuthUrl='/api/oauth/telegram/bind'
                      botName={status.telegram_bot_name}
                    />
                  </div>
                </div>
              </Modal>

              {/* LinuxDO绑定 */}
              <Card className='!rounded-xl'>
                <div className='flex items-center justify-between gap-3'>
                  <div className='flex items-center flex-1 min-w-0'>
                    <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                      <SiLinux
                        size={20}
                        className='text-slate-600 dark:text-slate-300'
                      />
                    </div>
                    <div className='flex-1 min-w-0'>
                      <div className='font-medium text-gray-900'>
                        {t('LinuxDO')}
                      </div>
                      <div className='text-sm text-gray-500 truncate'>
                        {renderAccountInfo(
                          userState.user?.linux_do_id,
                          t('LinuxDO ID'),
                        )}
                      </div>
                    </div>
                  </div>
                  <div className='flex-shrink-0'>
                    <Button
                      type='primary'
                      theme='outline'
                      size='small'
                      onClick={() =>
                        onLinuxDOOAuthClicked(status.linuxdo_client_id)
                      }
                      disabled={
                        isBound(userState.user?.linux_do_id) ||
                        !status.linuxdo_oauth
                      }
                    >
                      {status.linuxdo_oauth ? t('绑定') : t('未启用')}
                    </Button>
                  </div>
                </div>
              </Card>

              {/* 自定义 OAuth 提供商绑定 */}
              {status.custom_oauth_providers &&
                status.custom_oauth_providers.map((provider) => {
                  const bound = isCustomOAuthBound(provider.id);
                  const binding = getCustomOAuthBinding(provider.id);
                  return (
                    <Card key={provider.slug} className='!rounded-xl'>
                      <div className='flex items-center justify-between gap-3'>
                        <div className='flex items-center flex-1 min-w-0'>
                          <div className='w-10 h-10 rounded-full bg-slate-100 dark:bg-slate-700 flex items-center justify-center mr-3 flex-shrink-0'>
                            {getOAuthProviderIcon(
                              provider.icon || binding?.provider_icon || '',
                              20,
                            )}
                          </div>
                          <div className='flex-1 min-w-0'>
                            <div className='font-medium text-gray-900'>
                              {provider.name}
                            </div>
                            <div className='text-sm text-gray-500 truncate'>
                              {bound
                                ? renderAccountInfo(
                                    binding?.provider_user_id,
                                    t('{{name}} ID', { name: provider.name }),
                                  )
                                : t('未绑定')}
                            </div>
                          </div>
                        </div>
                        <div className='flex-shrink-0'>
                          {bound ? (
                            <Button
                              type='danger'
                              theme='outline'
                              size='small'
                              loading={customOAuthLoading[provider.id]}
                              onClick={() =>
                                handleUnbindCustomOAuth(provider.id, provider.name)
                              }
                            >
                              {t('解绑')}
                            </Button>
                          ) : (
                            <Button
                              type='primary'
                              theme='outline'
                              size='small'
                              onClick={() => handleBindCustomOAuth(provider)}
                            >
                              {t('绑定')}
                            </Button>
                          )}
                        </div>
                      </div>
                    </Card>
                  );
                })}
            </div>
          </div>
        </TabPane>

        {/* 安全设置 Tab */}
        <TabPane
          tab={
            <div className='flex items-center'>
              <ShieldCheck size={16} className='mr-2' />
              {t('安全设置')}
            </div>
          }
          itemKey='security'
        >
          <div className='py-4'>
            <div className='space-y-6'>
              <Space vertical className='w-full'>
                {/* 系统访问令牌 */}
                <Card className='!rounded-xl w-full'>
                  <div className='flex flex-col sm:flex-row items-start sm:justify-between gap-4'>
                    <div className='flex items-start w-full sm:w-auto'>
                      <div className='w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mr-4 flex-shrink-0'>
                        <IconKey size='large' className='text-slate-600' />
                      </div>
                      <div className='flex-1'>
                        <Typography.Title heading={6} className='mb-1'>
                          {t('系统访问令牌')}
                        </Typography.Title>
                        <Typography.Text type='tertiary' className='text-sm'>
                          {t('用于API调用的身份验证令牌，请妥善保管')}
                        </Typography.Text>
                        {systemToken && (
                          <div className='mt-3'>
                            <Input
                              readonly
                              value={systemToken}
                              onClick={handleSystemTokenClick}
                              size='large'
                              prefix={<IconKey />}
                            />
                          </div>
                        )}
                      </div>
                    </div>
                    <Button
                      type='primary'
                      theme='solid'
                      onClick={generateAccessToken}
                      className='!bg-slate-600 hover:!bg-slate-700 w-full sm:w-auto'
                      icon={<IconKey />}
                    >
                      {systemToken ? t('重新生成') : t('生成令牌')}
                    </Button>
                  </div>
                </Card>

                {/* 密码管理 */}
                <Card className='!rounded-xl w-full'>
                  <div className='flex flex-col sm:flex-row items-start sm:justify-between gap-4'>
                    <div className='flex items-start w-full sm:w-auto'>
                      <div className='w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mr-4 flex-shrink-0'>
                        <IconLock size='large' className='text-slate-600' />
                      </div>
                      <div>
                        <Typography.Title heading={6} className='mb-1'>
                          {t('密码管理')}
                        </Typography.Title>
                        <Typography.Text type='tertiary' className='text-sm'>
                          {t('定期更改密码可以提高账户安全性')}
                        </Typography.Text>
                      </div>
                    </div>
                    <Button
                      type='primary'
                      theme='solid'
                      onClick={() => setShowChangePasswordModal(true)}
                      className='!bg-slate-600 hover:!bg-slate-700 w-full sm:w-auto'
                      icon={<IconLock />}
                    >
                      {t('修改密码')}
                    </Button>
                  </div>
                </Card>

                {/* Passkey 设置 */}
                <Card className='!rounded-xl w-full'>
                  <div className='flex flex-col sm:flex-row items-start sm:justify-between gap-4'>
                    <div className='flex items-start w-full sm:w-auto'>
                      <div className='w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mr-4 flex-shrink-0'>
                        <IconKey size='large' className='text-slate-600' />
                      </div>
                      <div>
                        <Typography.Title heading={6} className='mb-1'>
                          {t('Passkey 登录')}
                        </Typography.Title>
                        <Typography.Text type='tertiary' className='text-sm'>
                          {passkeyEnabled
                            ? t('已启用 Passkey，无需密码即可登录')
                            : t('使用 Passkey 实现免密且更安全的登录体验')}
                        </Typography.Text>
                        <div className='mt-2 text-xs text-gray-500 space-y-1'>
                          <div>
                            {t('最后使用时间')}：{lastUsedLabel}
                          </div>
                          {/*{passkeyEnabled && (*/}
                          {/*  <div>*/}
                          {/*    {t('备份支持')}：*/}
                          {/*    {passkeyStatus?.backup_eligible*/}
                          {/*      ? t('支持备份')*/}
                          {/*      : t('不支持')}*/}
                          {/*    ，{t('备份状态')}：*/}
                          {/*    {passkeyStatus?.backup_state ? t('已备份') : t('未备份')}*/}
                          {/*  </div>*/}
                          {/*)}*/}
                          {!passkeySupported && (
                            <div className='text-amber-600'>
                              {t('当前设备不支持 Passkey')}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                    <Button
                      type={passkeyEnabled ? 'danger' : 'primary'}
                      theme={passkeyEnabled ? 'solid' : 'solid'}
                      onClick={
                        passkeyEnabled
                          ? () => {
                              Modal.confirm({
                                title: t('确认解绑 Passkey'),
                                content: t(
                                  '解绑后将无法使用 Passkey 登录，确定要继续吗？',
                                ),
                                okText: t('确认解绑'),
                                cancelText: t('取消'),
                                okType: 'danger',
                                onOk: onPasskeyDelete,
                              });
                            }
                          : onPasskeyRegister
                      }
                      className={`w-full sm:w-auto ${passkeyEnabled ? '!bg-slate-500 hover:!bg-slate-600' : ''}`}
                      icon={<IconKey />}
                      disabled={!passkeySupported && !passkeyEnabled}
                      loading={
                        passkeyEnabled
                          ? passkeyDeleteLoading
                          : passkeyRegisterLoading
                      }
                    >
                      {passkeyEnabled ? t('解绑 Passkey') : t('注册 Passkey')}
                    </Button>
                  </div>
                </Card>

                {/* 两步验证设置 */}
                <TwoFASetting t={t} />

                {/* 危险区域 */}
                <Card className='!rounded-xl w-full'>
                  <div className='flex flex-col sm:flex-row items-start sm:justify-between gap-4'>
                    <div className='flex items-start w-full sm:w-auto'>
                      <div className='w-12 h-12 rounded-full bg-slate-100 flex items-center justify-center mr-4 flex-shrink-0'>
                        <IconDelete size='large' className='text-slate-600' />
                      </div>
                      <div>
                        <Typography.Title
                          heading={6}
                          className='mb-1 text-slate-700'
                        >
                          {t('删除账户')}
                        </Typography.Title>
                        <Typography.Text type='tertiary' className='text-sm'>
                          {t('此操作不可逆，所有数据将被永久删除')}
                        </Typography.Text>
                      </div>
                    </div>
                    <Button
                      type='danger'
                      theme='solid'
                      onClick={() => setShowAccountDeleteModal(true)}
                      className='w-full sm:w-auto !bg-slate-500 hover:!bg-slate-600'
                      icon={<IconDelete />}
                    >
                      {t('删除账户')}
                    </Button>
                  </div>
                </Card>
              </Space>
            </div>
          </div>
        </TabPane>
      </Tabs>
    </Card>
  );
};

export default AccountManagement;
