// web/src/lib/components/dashboard/CheckinCalendar.svelte
<svelte:options runes={false} />

<script>
  import { apiGet, apiPost } from '$lib/api';
  import { showError, showSuccess } from '$lib/dashboard/notify.js';
  import { renderQuota } from '$lib/dashboard/helpers.js';
  import { CalendarCheck, Gift, Check, CaretDown, CaretUp } from 'phosphor-svelte';
  import TurnstileWidget from './TurnstileWidget.svelte';
  import * as Dialog from '$lib/components/ui/dialog';

  /** @type {Record<string, any>} */
  export let status = {};
  export let turnstileEnabled = false;
  export let turnstileSiteKey = '';

  let loading = false;
  let checkinLoading = false;
  let turnstileModalVisible = false;
  let turnstileKey = 0;

  let checkinData = {
    enabled: false,
    stats: {
      checked_in_today: false,
      total_checkins: 0,
      total_quota: 0,
      checkin_count: 0,
      records: [],
    },
  };

  let viewDate = new Date();
  let initialLoaded = false;
  /** @type {boolean | null} */
  let isCollapsed = null;

  $: currentMonth = `${viewDate.getFullYear()}-${String(viewDate.getMonth() + 1).padStart(2, '0')}`;

  $: checkinRecordsMap = (() => {
    const map = {};
    const records = checkinData.stats?.records || [];
    records.forEach((record) => {
      map[record.checkin_date] = record.quota_awarded;
    });
    return map;
  })();

  $: monthlyQuota = (checkinData.stats?.records || []).reduce(
    (sum, record) => sum + (record.quota_awarded || 0),
    0,
  );

  async function fetchCheckinStatus(month) {
    const isFirstLoad = !initialLoaded;
    loading = true;
    try {
      const res = await apiGet(`/api/user/checkin?month=${encodeURIComponent(month)}`);
      if (res?.success) {
        checkinData = res.data;
        if (isFirstLoad) {
          isCollapsed = res.data.stats?.checked_in_today ?? false;
          initialLoaded = true;
        }
      } else {
        showError(res?.message || '获取签到状态失败');
        if (isFirstLoad) {
          isCollapsed = false;
          initialLoaded = true;
        }
      }
    } catch (_) {
      showError('获取签到状态失败');
      if (isFirstLoad) {
        isCollapsed = false;
        initialLoaded = true;
      }
    } finally {
      loading = false;
    }
  }

  /**
   * @param {string} [token]
   */
  async function postCheckin(token) {
    const url = token
      ? `/api/user/checkin?turnstile=${encodeURIComponent(token)}`
      : '/api/user/checkin';
    return apiPost(url, {});
  }

  /**
   * @param {any} message
   */
  function shouldTriggerTurnstile(message) {
    if (!turnstileEnabled) return false;
    if (typeof message !== 'string') return true;
    return message.includes('Turnstile');
  }

  /**
   * @param {string} [token]
   */
  async function doCheckin(token) {
    checkinLoading = true;
    try {
      const res = await postCheckin(token);
      if (res?.success) {
        showSuccess('签到成功！获得 ' + renderQuota(res.data.quota_awarded));
        await fetchCheckinStatus(currentMonth);
        turnstileModalVisible = false;
      } else {
        const message = res?.message;
        if (!token && shouldTriggerTurnstile(message)) {
          if (!turnstileSiteKey) {
            showError('Turnstile is enabled but site key is empty.');
            return;
          }
          turnstileModalVisible = true;
          return;
        }
        if (token && shouldTriggerTurnstile(message)) {
          turnstileKey += 1;
        }
        showError(message || '签到失败');
      }
    } catch (_) {
      showError('签到失败');
    } finally {
      checkinLoading = false;
    }
  }

  function prevMonth() {
    const d = new Date(viewDate);
    d.setMonth(d.getMonth() - 1);
    viewDate = d;
  }

  function nextMonth() {
    const d = new Date(viewDate);
    d.setMonth(d.getMonth() + 1);
    viewDate = d;
  }

  $: if (status?.checkin_enabled) {
    fetchCheckinStatus(currentMonth);
  }

  const weekdays = ['日', '一', '二', '三', '四', '五', '六'];

  /**
   * Build grid cells for month view
   * @param {Date} d
   */
  function buildMonthGrid(d) {
    const year = d.getFullYear();
    const month = d.getMonth();
    const first = new Date(year, month, 1);
    const startPad = first.getDay();
    const lastDay = new Date(year, month + 1, 0).getDate();
    /** @type {({ day: number; inMonth: boolean; dateStr: string } | null)[]} */
    const cells = [];
    for (let i = 0; i < startPad; i++) cells.push(null);
    for (let day = 1; day <= lastDay; day++) {
      const ds = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      cells.push({ day, inMonth: true, dateStr: ds });
    }
    while (cells.length % 7 !== 0) cells.push(null);
    return cells;
  }

  $: monthCells = buildMonthGrid(viewDate);
</script>

{#if status?.checkin_enabled}
  <div class="w-full min-w-0 rounded-2xl border border-gray-200 bg-card p-4 shadow-sm dark:border-zinc-700 md:p-6">
    <Dialog.Root bind:open={turnstileModalVisible}>
      <Dialog.Content class="max-w-md">
        <Dialog.Header>
          <Dialog.Title>Security Check</Dialog.Title>
        </Dialog.Header>
        <div class="flex justify-center py-2">
          {#key turnstileKey}
            <TurnstileWidget
              sitekey={turnstileSiteKey}
              onVerify={(t) => doCheckin(t)}
            />
          {/key}
        </div>
      </Dialog.Content>
    </Dialog.Root>

    <div class="flex items-center justify-between gap-3">
      <button
        type="button"
        class="flex min-w-0 flex-1 cursor-pointer items-center text-left"
        on:click={() => (isCollapsed = !isCollapsed)}
      >
        <div
          class="mr-3 flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-green-600/15 text-green-700 dark:text-green-400"
        >
          <CalendarCheck size={18} weight="duotone" />
        </div>
        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-2">
            <span class="text-lg font-medium">每日签到</span>
            {#if isCollapsed}
              <CaretDown size={16} class="text-muted-foreground" />
            {:else}
              <CaretUp size={16} class="text-muted-foreground" />
            {/if}
          </div>
          <div class="text-xs text-muted-foreground">
            {#if !initialLoaded}
              正在加载签到状态...
            {:else if checkinData.stats?.checked_in_today}
              今日已签到，累计签到 {checkinData.stats?.total_checkins || 0} 天
            {:else}
              每日签到可获得随机额度奖励
            {/if}
          </div>
        </div>
      </button>
      <button
        type="button"
        class="btn-primary inline-flex shrink-0 items-center gap-1.5 rounded-none bg-green-700 px-3 py-2 text-sm text-white hover:bg-green-800 disabled:opacity-60"
        on:click={() => doCheckin()}
        disabled={checkinLoading || !initialLoaded || checkinData.stats?.checked_in_today}
      >
        <Gift size={16} />
        {#if !initialLoaded}
          加载中...
        {:else if checkinData.stats?.checked_in_today}
          今日已签到
        {:else}
          立即签到
        {/if}
      </button>
    </div>

    {#if isCollapsed === false}
      <div class="mt-4 space-y-4">
        <div class="grid grid-cols-3 gap-3">
          <div class="rounded-lg bg-muted/50 p-2.5 text-center">
            <div class="text-xl font-bold text-green-600">{checkinData.stats?.total_checkins || 0}</div>
            <div class="text-xs text-muted-foreground">累计签到</div>
          </div>
          <div class="rounded-lg bg-muted/50 p-2.5 text-center">
            <div class="text-xl font-bold text-orange-600">{renderQuota(monthlyQuota, 6)}</div>
            <div class="text-xs text-muted-foreground">本月获得</div>
          </div>
          <div class="rounded-lg bg-muted/50 p-2.5 text-center">
            <div class="text-xl font-bold text-blue-600">{renderQuota(checkinData.stats?.total_quota || 0, 6)}</div>
            <div class="text-xs text-muted-foreground">累计获得</div>
          </div>
        </div>

        <div class="overflow-hidden rounded-lg border border-border">
          <div class="flex items-center justify-between border-b border-border bg-muted/40 px-3 py-2">
            <button type="button" class="text-sm hover:underline" on:click={prevMonth}>←</button>
            <span class="text-sm font-medium"
              >{viewDate.getFullYear()} 年 {viewDate.getMonth() + 1} 月</span
            >
            <button type="button" class="text-sm hover:underline" on:click={nextMonth}>→</button>
          </div>
          {#if loading}
            <div class="p-6 text-center text-sm text-muted-foreground">加载中...</div>
          {:else}
            <div class="grid grid-cols-7 gap-px bg-border p-1 text-center text-[11px]">
              {#each weekdays as w}
                <div class="bg-muted/30 py-1 font-medium text-muted-foreground">{w}</div>
              {/each}
              {#each monthCells as cell}
                {#if cell === null}
                  <div class="min-h-[52px] bg-background"></div>
                {:else}
                  {@const q = checkinRecordsMap[cell.dateStr]}
                  <div
                    class="relative min-h-[52px] border border-transparent bg-background p-0.5 text-left"
                    title={q != null ? `获得 ${renderQuota(q)}` : ''}
                  >
                    <span class="absolute left-1 top-0.5 text-[11px] text-muted-foreground">{cell.day}</span>
                    {#if q != null}
                      <div class="flex h-full flex-col items-center justify-center pt-3">
                        <div
                          class="mb-0.5 flex h-6 w-6 items-center justify-center rounded-full bg-green-600 shadow-sm"
                        >
                          <Check size={14} class="text-white" weight="bold" />
                        </div>
                        <div class="text-[10px] font-medium leading-none text-green-700 dark:text-green-400">
                          {renderQuota(q)}
                        </div>
                      </div>
                    {/if}
                  </div>
                {/if}
              {/each}
            </div>
          {/if}
        </div>

        <div class="rounded-lg bg-muted/40 p-2.5 text-xs text-muted-foreground">
          <ul class="list-inside list-disc space-y-0.5">
            <li>每日签到可获得随机额度奖励</li>
            <li>签到奖励将直接添加到您的账户余额</li>
            <li>每日仅可签到一次，请勿重复签到</li>
          </ul>
        </div>
      </div>
    {/if}
  </div>
{/if}

// web/src/components/settings/personal/cards/CheckinCalendar.jsx
import React, { useState, useEffect, useMemo } from 'react';
import {
  Card,
  Calendar,
  Button,
  Typography,
  Avatar,
  Spin,
  Tooltip,
  Collapsible,
  Modal,
} from '@douyinfe/semi-ui';
import {
  CalendarCheck,
  Gift,
  Check,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';
import Turnstile from 'react-turnstile';
import { API, showError, showSuccess, renderQuota } from '../../../../helpers';

const CheckinCalendar = ({ t, status, turnstileEnabled, turnstileSiteKey }) => {
  const [loading, setLoading] = useState(false);
  const [checkinLoading, setCheckinLoading] = useState(false);
  const [turnstileModalVisible, setTurnstileModalVisible] = useState(false);
  const [turnstileWidgetKey, setTurnstileWidgetKey] = useState(0);
  const [checkinData, setCheckinData] = useState({
    enabled: false,
    stats: {
      checked_in_today: false,
      total_checkins: 0,
      total_quota: 0,
      checkin_count: 0,
      records: [],
    },
  });
  const [currentMonth, setCurrentMonth] = useState(
    new Date().toISOString().slice(0, 7),
  );
  // 初始加载状态，用于避免折叠状态闪烁
  const [initialLoaded, setInitialLoaded] = useState(false);
  // 折叠状态：null 表示未确定（等待首次加载）
  const [isCollapsed, setIsCollapsed] = useState(null);

  // 创建日期到额度的映射，方便快速查找
  const checkinRecordsMap = useMemo(() => {
    const map = {};
    const records = checkinData.stats?.records || [];
    records.forEach((record) => {
      map[record.checkin_date] = record.quota_awarded;
    });
    return map;
  }, [checkinData.stats?.records]);

  // 计算本月获得的额度
  const monthlyQuota = useMemo(() => {
    const records = checkinData.stats?.records || [];
    return records.reduce(
      (sum, record) => sum + (record.quota_awarded || 0),
      0,
    );
  }, [checkinData.stats?.records]);

  // 获取签到状态
  const fetchCheckinStatus = async (month) => {
    const isFirstLoad = !initialLoaded;
    setLoading(true);
    try {
      const res = await API.get(`/api/user/checkin?month=${month}`);
      const { success, data, message } = res.data;
      if (success) {
        setCheckinData(data);
        // 首次加载时，根据签到状态设置折叠状态
        if (isFirstLoad) {
          setIsCollapsed(data.stats?.checked_in_today ?? false);
          setInitialLoaded(true);
        }
      } else {
        showError(message || "获取签到状态失败");
        if (isFirstLoad) {
          setIsCollapsed(false);
          setInitialLoaded(true);
        }
      }
    } catch (error) {
      showError("获取签到状态失败");
      if (isFirstLoad) {
        setIsCollapsed(false);
        setInitialLoaded(true);
      }
    } finally {
      setLoading(false);
    }
  };

  const postCheckin = async (token) => {
    const url = token
      ? `/api/user/checkin?turnstile=${encodeURIComponent(token)}`
      : '/api/user/checkin';
    return API.post(url);
  };

  const shouldTriggerTurnstile = (message) => {
    if (!turnstileEnabled) return false;
    if (typeof message !== 'string') return true;
    return message.includes('Turnstile');
  };

  const doCheckin = async (token) => {
    setCheckinLoading(true);
    try {
      const res = await postCheckin(token);
      const { success, data, message } = res.data;
      if (success) {
        showSuccess(
          "签到成功！获得" + ' ' + renderQuota(data.quota_awarded),
        );
        // 刷新签到状态
        fetchCheckinStatus(currentMonth);
        setTurnstileModalVisible(false);
      } else {
        if (!token && shouldTriggerTurnstile(message)) {
          if (!turnstileSiteKey) {
            showError('Turnstile is enabled but site key is empty.');
            return;
          }
          setTurnstileModalVisible(true);
          return;
        }
        if (token && shouldTriggerTurnstile(message)) {
          setTurnstileWidgetKey((v) => v + 1);
        }
        showError(message || "签到失败");
      }
    } catch (error) {
      showError("签到失败");
    } finally {
      setCheckinLoading(false);
    }
  };

  useEffect(() => {
    if (status?.checkin_enabled) {
      fetchCheckinStatus(currentMonth);
    }
  }, [status?.checkin_enabled, currentMonth]);

  // 如果签到功能未启用，不显示组件
  if (!status?.checkin_enabled) {
    return null;
  }

  // 日期渲染函数 - 显示签到状态和获得的额度
  const dateRender = (dateString) => {
    // Semi Calendar 传入的 dateString 是 Date.toString() 格式
    // 需要转换为 YYYY-MM-DD 格式来匹配后端数据
    const date = new Date(dateString);
    if (isNaN(date.getTime())) {
      return null;
    }
    // 使用本地时间格式化，避免时区问题
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const formattedDate = `${year}-${month}-${day}`; // YYYY-MM-DD
    const quotaAwarded = checkinRecordsMap[formattedDate];
    const isCheckedIn = quotaAwarded !== undefined;

    if (isCheckedIn) {
      return (
        <Tooltip
          content={`${"获得"} ${renderQuota(quotaAwarded)}`}
          position='top'
        >
          <div className='absolute inset-0 flex flex-col items-center justify-center cursor-pointer'>
            <div className='w-6 h-6 rounded-full bg-green-500 flex items-center justify-center mb-0.5 shadow-sm'>
              <Check size={14} className='text-white' strokeWidth={3} />
            </div>
            <div className='text-[10px] font-medium text-green-600 dark:text-green-400 leading-none'>
              {renderQuota(quotaAwarded)}
            </div>
          </div>
        </Tooltip>
      );
    }
    return null;
  };

  // 处理月份变化
  const handleMonthChange = (date) => {
    const month = date.toISOString().slice(0, 7);
    setCurrentMonth(month);
  };

  return (
    <Card className='!rounded-2xl'>
      <Modal
        title='Security Check'
        visible={turnstileModalVisible}
        footer={null}
        centered
        onCancel={() => {
          setTurnstileModalVisible(false);
          setTurnstileWidgetKey((v) => v + 1);
        }}
      >
        <div className='flex justify-center py-2'>
          <Turnstile
            key={turnstileWidgetKey}
            sitekey={turnstileSiteKey}
            onVerify={(token) => {
              doCheckin(token);
            }}
            onExpire={() => {
              setTurnstileWidgetKey((v) => v + 1);
            }}
          />
        </div>
      </Modal>

      {/* 卡片头部 */}
      <div className='flex items-center justify-between'>
        <div
          className='flex items-center flex-1 cursor-pointer'
          onClick={() => setIsCollapsed(!isCollapsed)}
        >
          <Avatar size='small' color='green' className='mr-3 shadow-md'>
            <CalendarCheck size={16} />
          </Avatar>
          <div className='flex-1'>
            <div className='flex items-center gap-2'>
              <Typography.Text className='text-lg font-medium'>
                {"每日签到"}
              </Typography.Text>
              {isCollapsed ? (
                <ChevronDown size={16} className='text-gray-400' />
              ) : (
                <ChevronUp size={16} className='text-gray-400' />
              )}
            </div>
            <div className='text-xs text-gray-500 dark:text-gray-400'>
              {!initialLoaded
                ? "正在加载签到状态..."
                : checkinData.stats?.checked_in_today
                  ? "今日已签到，累计签到" +
                    ` ${checkinData.stats?.total_checkins || 0} ` +
                    "天"
                  : "每日签到可获得随机额度奖励"}
            </div>
          </div>
        </div>
        <Button
          type='primary'
          theme='solid'
          icon={<Gift size={16} />}
          onClick={() => doCheckin()}
          loading={checkinLoading || !initialLoaded}
          disabled={!initialLoaded || checkinData.stats?.checked_in_today}
          className='!bg-green-600 hover:!bg-green-700'
        >
          {!initialLoaded
            ? "加载中..."
            : checkinData.stats?.checked_in_today
              ? "今日已签到"
              : "立即签到"}
        </Button>
      </div>

      {/* 可折叠内容 */}
      <Collapsible isOpen={isCollapsed === false} keepDOM>
        {/* 签到统计 */}
        <div className='grid grid-cols-3 gap-3 mb-4 mt-4'>
          <div className='text-center p-2.5 bg-slate-50 dark:bg-slate-800 rounded-lg'>
            <div className='text-xl font-bold text-green-600'>
              {checkinData.stats?.total_checkins || 0}
            </div>
            <div className='text-xs text-gray-500'>{"累计签到"}</div>
          </div>
          <div className='text-center p-2.5 bg-slate-50 dark:bg-slate-800 rounded-lg'>
            <div className='text-xl font-bold text-orange-600'>
              {renderQuota(monthlyQuota, 6)}
            </div>
            <div className='text-xs text-gray-500'>{"本月获得"}</div>
          </div>
          <div className='text-center p-2.5 bg-slate-50 dark:bg-slate-800 rounded-lg'>
            <div className='text-xl font-bold text-blue-600'>
              {renderQuota(checkinData.stats?.total_quota || 0, 6)}
            </div>
            <div className='text-xs text-gray-500'>{"累计获得"}</div>
          </div>
        </div>

        {/* 签到日历 - 使用更紧凑的样式 */}
        <Spin spinning={loading}>
          <div className='border rounded-lg overflow-hidden checkin-calendar'>
            <style>{`
            .checkin-calendar .semi-calendar {
              font-size: 13px;
            }
            .checkin-calendar .semi-calendar-month-header {
              padding: 8px 12px;
            }
            .checkin-calendar .semi-calendar-month-week-row {
              height: 28px;
            }
            .checkin-calendar .semi-calendar-month-week-row th {
              font-size: 12px;
              padding: 4px 0;
            }
            .checkin-calendar .semi-calendar-month-grid-row {
              height: auto;
            }
            .checkin-calendar .semi-calendar-month-grid-row td {
              height: 56px;
              padding: 2px;
            }
            .checkin-calendar .semi-calendar-month-grid-row-cell {
              position: relative;
              height: 100%;
            }
            .checkin-calendar .semi-calendar-month-grid-row-cell-day {
              position: absolute;
              top: 4px;
              left: 50%;
              transform: translateX(-50%);
              font-size: 12px;
              z-index: 1;
            }
            .checkin-calendar .semi-calendar-month-same {
              background: transparent;
            }
            .checkin-calendar .semi-calendar-month-today .semi-calendar-month-grid-row-cell-day {
              background: var(--semi-color-primary);
              color: white;border-radius: 50%;
              width: 20px;
              height: 20px;
              display: flex;
              align-items: center;
              justify-content: center;}
          `}</style>
            <Calendar
              mode='month'
              onChange={handleMonthChange}
              dateGridRender={(dateString, date) => dateRender(dateString)}
            />
          </div>
        </Spin>

        {/* 签到说明 */}
        <div className='mt-3 p-2.5 bg-slate-50 dark:bg-slate-800 rounded-lg'>
          <Typography.Text type='tertiary' className='text-xs'>
            <ul className='list-disc list-inside space-y-0.5'>
              <li>{"每日签到可获得随机额度奖励"}</li>
              <li>{"签到奖励将直接添加到您的账户余额"}</li>
              <li>{"每日仅可签到一次，请勿重复签到"}</li>
            </ul>
          </Typography.Text>
        </div>
      </Collapsible>
    </Card>
  );
};

export default CheckinCalendar;
